-- Seed data for leaders (Members of Parliament)
insert into public.leaders (name, position, county, constituency, party, term, allegations_count, projects_overseen, budget_managed, accountability_score, phone, email, photo_url, recent_actions, key_projects, social_twitter, social_facebook)
values
  ('Adagala, Beatrice Kahai', 'Member of Parliament', 'Vihiga', 'Vihiga (CWR)', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Denar, Joseph Hamisi', 'Member of Parliament', 'Kenya', 'Nominated', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gimose, Charles Gumini', 'Member of Parliament', 'Vihiga', 'Hamisi', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ikana, Frederick Lusuli', 'Member of Parliament', 'Kakamega', 'Shinyalu', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kagesi, Kivai Ernest Ogesi', 'Member of Parliament', 'Vihiga', 'Vihiga', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Omboko, Milemba Jeremiah', 'Member of Parliament', 'Vihiga', 'Emuhaya', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Tandaza, Kassim Sawa', 'Member of Parliament', 'Kwale', 'Matuga', 'ANC', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Koech, Victor Kipngetich', 'Member of Parliament', 'Bomet', 'Chepalungu', 'CCM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Barasa, Patrick Simiyu', 'Member of Parliament', 'Trans Nzoia', 'Cherangany', 'DAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bisau, Maurice Kakai', 'Member of Parliament', 'Trans Nzoia', 'Kiminini', 'DAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oyugi, Dick Maungu', 'Member of Parliament', 'Vihiga', 'Luanda', 'DAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Salasya, Peter Kalerwa', 'Member of Parliament', 'Kakamega', 'Mumias East', 'DAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wamboka, Nelson Jack Wamboka', 'Member of Parliament', 'Bungoma', 'Bumula', 'DAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kalasinga, Joseph Simiyu Wekesa Majimbo', 'Member of Parliament', 'Bungoma', 'Kabuchai', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Makali, John Okwisia', 'Member of Parliament', 'Bungoma', 'Kanduyi', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Murumba, John Chikati', 'Member of Parliament', 'Bungoma', 'Tongaren', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wambilianga, Catherine Nanjala', 'Member of Parliament', 'Busia', 'Busia (CWR)', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wanyonyi, Ferdinand Kevin', 'Member of Parliament', 'Trans Nzoia', 'Kwanza', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wanyonyi, Martin Pepela', 'Member of Parliament', 'Bungoma', 'Webuye West', 'FORD-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muli, Fabian Kyule', 'Member of Parliament', 'Machakos', 'Kangundo', 'GDDP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdul, Rahim Dawood', 'Member of Parliament', 'Meru', 'North Imenti', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ahmed, Shakeel Ahmed Shabbir', 'Member of Parliament', 'Kisumu', 'Kisumu East', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Caroline, Jeptoo Ng’elechei', 'Member of Parliament', 'Elgeyo Marakwet', 'Elgeyo Marakwet (CWR)', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Karauri, Ronald Kamwiko', 'Member of Parliament', 'Nairobi', 'Kasarani', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kitilai, Ole Ntutu', 'Member of Parliament', 'Narok', 'Narok South', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kururia, Elijah Njore Njoroge', 'Member of Parliament', 'Kiambu', 'Gatundu North', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Marubu, Monicah Muthoni', 'Member of Parliament', 'Lamu', 'Lamu (CWR)', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohammed, Fatuma Zainabu', 'Member of Parliament', 'Migori', 'Migori (CWR)', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mulanya, Geoffrey Ekesa', 'Member of Parliament', 'Busia', 'Nambale', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwalyo, Joshua Mbithi Mutua', 'Member of Parliament', 'Machakos', 'Masinga', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nebart, Bernard Muriuki', 'Member of Parliament', 'Embu', 'Mbeere South', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Toroitich, Timothy Kipchumba', 'Member of Parliament', 'Elgeyo Marakwet', 'Marakwet West', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdirahman, Mohamed Abdi', 'Member of Parliament', 'Mandera', 'Lafey', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Arama, Samuel', 'Member of Parliament', 'Nakuru', 'Nakuru Town West', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bonaya, Mumina Gollo', 'Member of Parliament', 'Isiolo', 'Isiolo (CWR)', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chege, Sabina Wanjiru', 'Member of Parliament', 'Kenya', 'Nominated', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Hassan, Abdi Yusuf', 'Member of Parliament', 'Nairobi', 'Kamkunji', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ithinji, Dr. Shadrack Mwiti', 'Member of Parliament', 'Meru', 'South Imenti', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Karitho, Kiili Daniel', 'Member of Parliament', 'Meru', 'Igembe Central', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiaraho, David Njuguna', 'Member of Parliament', 'Nyandarua', 'Ol Kalou', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Korere, Sarah Paulata', 'Member of Parliament', 'Laikipia', 'Laikipia North', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Koyi, John Waluke', 'Member of Parliament', 'Bungoma', 'Sirisia', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kwenya, Thuku Zachary', 'Member of Parliament', 'Nyandarua', 'Kinangop', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lomwa, Joseph Samal', 'Member of Parliament', 'Isiolo', 'Isiolo North', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Maina, Mwago Amos', 'Member of Parliament', 'Nairobi', 'Starehe', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mogaka, Stephen M.', 'Member of Parliament', 'Nyamira', 'West Mugirango', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohamed, Aden Daudi', 'Member of Parliament', 'Wajir', 'Wajir East', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mongina, Jerusha Momanyi', 'Member of Parliament', 'Nyamira', 'Nyamira (CWR)', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mrembo, Irene Njoki', 'Member of Parliament', 'Nakuru', 'Bahati', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muiruri, Muthama Stanley', 'Member of Parliament', 'Lamu', 'Lamu West', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwenje, Mark Samuel Muriithi', 'Member of Parliament', 'Nairobi', 'Embakasi West', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ngikolong, Nicholas Ng’ikor Nixon', 'Member of Parliament', 'Turkana', 'Turkana East', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyamai, Rachael Kaki', 'Member of Parliament', 'Kitui', 'Kitui South', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Obo, Ruweida Mohamed', 'Member of Parliament', 'Lamu', 'Lamu East', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Pareiyo, Agnes Mantaine', 'Member of Parliament', 'Narok', 'Narok North', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Shake, Peter Mbogho', 'Member of Parliament', 'Taita Taveta', 'Mwatate', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Shurie, Abdi Omar', 'Member of Parliament', 'Garissa', 'Balambala', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Siyad, Amina Udgoon', 'Member of Parliament', 'Garissa', 'Garissa (CWR)', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Vacant', 'Member of Parliament', 'Isiolo', 'Isiolo South', 'Independent', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wehliye, Adan Keynan', 'Member of Parliament', 'Wajir', 'Eldas', 'JP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdullahi, Amina Dika', 'Member of Parliament', 'Tana River', 'Tana River (CWR)', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Guyo, Adhe Wario', 'Member of Parliament', 'Marsabit', 'North Horr', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kassait, William Kamket', 'Member of Parliament', 'Baringo', 'Tiaty', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lentoijoni, Jackson Lekumontare', 'Member of Parliament', 'Samburu', 'Samburu East', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lesuuda, Josephine Naisula', 'Member of Parliament', 'Samburu', 'Samburu West', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sunkuli, Julius Lekakeny Ole', 'Member of Parliament', 'Narok', 'Kilgoris', 'KANU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kasiwai, Rael Chepkemoi', 'Member of Parliament', 'West Pokot', 'West Pokot (CWR)', 'KUP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Pkosing, David Losiakou', 'Member of Parliament', 'West Pokot', 'Pokot South', 'KUP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Titus, Lotee', 'Member of Parliament', 'West Pokot', 'Kacheliba', 'KUP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mule, Caleb Mutiso', 'Member of Parliament', 'Machakos', 'Machakos Town', 'MCCP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mutuse, Eckomas Mwengi', 'Member of Parliament', 'Makueni', 'Kibwezi West', 'MCCP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ochieng, David Ouma', 'Member of Parliament', 'Siaya', 'Ugenya', 'MDG', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdi, Abdi Ali', 'Member of Parliament', 'Garissa', 'Ijara', 'NAP-K', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Aburi, Lawrence Mpuru', 'Member of Parliament', 'Meru', 'Tigania East', 'NOPEU', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdirahman, Husseinweytan Mohamed', 'Member of Parliament', 'Mandera', 'Mandera East', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abuor, Paul', 'Member of Parliament', 'Migori', 'Rongo', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Adow, Mohamed Aden', 'Member of Parliament', 'Wajir', 'Wajir South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Amollo, Paul Otiende', 'Member of Parliament', 'Siaya', 'Rarieda', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Atandi Samuel Onunga', 'Member of Parliament', 'Siaya', 'Alego Usonga', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bady, Bady Twalib', 'Member of Parliament', 'Mombasa', 'Jomvu', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Barongo, Nolfason Obadiah', 'Member of Parliament', 'Kisii', 'Bomachoge Borabu', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bedzimba, Rashid Juma', 'Member of Parliament', 'Mombasa', 'Kisauni', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Busia, Ruth Adhiambo Odinga', 'Member of Parliament', 'Kisumu', 'Kisumu (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Buyu, Rozaah Akinyi', 'Member of Parliament', 'Kisumu', 'Kisumu West', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chimba, Zamzam Mohamed', 'Member of Parliament', 'Mombasa', 'Mombasa (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Elachi, Beatrice Kadeveresia', 'Member of Parliament', 'Nairobi', 'Dagoretti North', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Farah, Yussuf Mohamed', 'Member of Parliament', 'Wajir', 'Wajir West', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Francis, Kajwang’ Tom Joseph', 'Member of Parliament', 'Nairobi', 'Ruaraka', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gisairo, Clive Ombane', 'Member of Parliament', 'Nyamira', 'Kitutu Masaba', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gogo, Lilian Achieng', 'Member of Parliament', 'Homa Bay', 'Rangwe', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Guyo, Ali Wario', 'Member of Parliament', 'Tana River', 'Garsen', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Hamisi, Kakuta Maimai', 'Member of Parliament', 'Kajiado', 'Kajiado East', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Hiribae, Said Buya', 'Member of Parliament', 'Tana River', 'Galole', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Jehow, Fatuma Abdi', 'Member of Parliament', 'Wajir', 'Wajir (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kaluma, George Peter Opondo', 'Member of Parliament', 'Homa Bay', 'Homa Bay Town', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kanchory, Elijah Memusi', 'Member of Parliament', 'Kajiado', 'Kajiado Central', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Katana, Paul Kahindi', 'Member of Parliament', 'Kilifi', 'Kaloleni', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Khodhe, Phelix Odiwuor', 'Member of Parliament', 'Nairobi', 'Langata', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kibagendi, Antoney', 'Member of Parliament', 'Kisii', 'Kitutu Chache South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipchumba, Harold Kimuge', 'Member of Parliament', 'Kenya', 'Nominated', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiti, Richard Ken Chonga', 'Member of Parliament', 'Kilifi', 'Kilifi South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kombe, Harrison Garama', 'Member of Parliament', 'Kilifi', 'Magarini', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Luyai, Caleb Amisi', 'Member of Parliament', 'Trans Nzoia', 'Saboti', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Machele, Mohamed Soud', 'Member of Parliament', 'Mombasa', 'Mvita', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Manduku, Daniel Ogwoka', 'Member of Parliament', 'Kisii', 'Nyaribari Masaba', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Masara, Peter Francis', 'Member of Parliament', 'Migori', 'Suna West', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Masito, Fatuma Hamisi', 'Member of Parliament', 'Kwale', 'Kwale (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mayaka, Irene Nyakerario', 'Member of Parliament', 'Kenya', 'Nominated', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mboko, Mishi Juma Khamisi', 'Member of Parliament', 'Mombasa', 'Likoni', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohamed, Abdikadir Hussein', 'Member of Parliament', 'Garissa', 'Lagdera', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohamed, Junet Sheikh Nuh', 'Member of Parliament', 'Migori', 'Suna East', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohamed, Umulkher Harun', 'Member of Parliament', 'Kenya', 'Nominated', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mugabe, Innocent Maino', 'Member of Parliament', 'Kakamega', 'Likuyani', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muhanda, Elsie Busihile', 'Member of Parliament', 'Kakamega', 'Kakamega (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mukhwana, Titus Khamala', 'Member of Parliament', 'Kakamega', 'Lurambi', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwale, Nicholas S. Tindi', 'Member of Parliament', 'Kakamega', 'Butere', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwanyanje, Gertrude Mbeyu', 'Member of Parliament', 'Kilifi', 'Kilifi (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mnyazi, Amina Laura', 'Member of Parliament', 'Kilifi', 'Malindi', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nabii, Nabwera Daraja', 'Member of Parliament', 'Kakamega', 'Lugari', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nabulindo, Peter Oscar', 'Member of Parliament', 'Kakamega', 'Matungu', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Naibun, Paul Ekwom', 'Member of Parliament', 'Turkana', 'Turkana North', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Naicca, Johnson Manya', 'Member of Parliament', 'Kakamega', 'Mumias West', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Namoit, John Ariko', 'Member of Parliament', 'Turkana', 'Turkana South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyamita, Mark Ogolla', 'Member of Parliament', 'Migori', 'Uriri', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyikal, James Wambura', 'Member of Parliament', 'Kisumu', 'Seme', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Obara, Eve Akinyi', 'Member of Parliament', 'Homa Bay', 'Kabondo Kasipul', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Odanga, Geoffrey Makokha', 'Member of Parliament', 'Busia', 'Matayos', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Odege, Tom Mboya', 'Member of Parliament', 'Migori', 'Nyatike', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Odhiambo, Elisha Ochieng', 'Member of Parliament', 'Siaya', 'Gem', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Odhiambo, Millie Grace Akoth', 'Member of Parliament', 'Homa Bay', 'Suba North', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Odoyo, Okello Jared', 'Member of Parliament', 'Kisumu', 'Nyando', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oduor, Christine Ombaka', 'Member of Parliament', 'Siaya', 'Siaya (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ogolla, Gideon Ochanda', 'Member of Parliament', 'Siaya', 'Bondo', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oku, Edward Kaunya', 'Member of Parliament', 'Busia', 'Teso North', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Okuome, Andrew Adipo', 'Member of Parliament', 'Homa Bay', 'Karachuonyo', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oluoch, Anthony Tom', 'Member of Parliament', 'Nairobi', 'Mathare', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Omanyo, Catherine Nakhabi', 'Member of Parliament', 'Busia', 'Busia (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Omondi, Caroli', 'Member of Parliament', 'Homa Bay', 'Suba South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Omondi, Moses Okoth', 'Member of Parliament', 'Siaya', 'Ugunja', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Omwera, George Aladwa', 'Member of Parliament', 'Nairobi', 'Makadara', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ongili, Babu Owino Paul', 'Member of Parliament', 'Nairobi', 'Embakasi East', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ong’ondo Boyd Were', 'Member of Parliament', 'Homa Bay', 'Kasipul', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Orero, Peter Ochieng', 'Member of Parliament', 'Nairobi', 'Kibra', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oron, Joshua Odongo', 'Member of Parliament', 'Kisumu', 'Kisumu Central', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Osero, Patrick Kibagendi', 'Member of Parliament', 'Nyamira', 'Borabu', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Osogo, Bensuda Joyce Atieno', 'Member of Parliament', 'Homa Bay', 'Homa Bay (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oundo, Wilberforce Ojiambo', 'Member of Parliament', 'Busia', 'Funyula', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Owino, John Walter', 'Member of Parliament', 'Migori', 'Awendo', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Owino, Martin Peters', 'Member of Parliament', 'Homa Bay', 'Ndhiwa', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Owuor, Joshua Aduma', 'Member of Parliament', 'Kisumu', 'Nyakach', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oyoo, James Onyango', 'Member of Parliament', 'Kisumu', 'Muhoroni', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Oyula, Joseph H. Maero', 'Member of Parliament', 'Busia', 'Butula', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Passaris, Esther Muthomi', 'Member of Parliament', 'Nairobi City', 'Nairobi City (CWR)', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sakimba, Parashina Samuel', 'Member of Parliament', 'Kajiado', 'Kajiado South', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Shimbwa, Omar Mwinyi', 'Member of Parliament', 'Mombasa', 'Changamwe', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Shinali, Bernard Masaka', 'Member of Parliament', 'Kakamega', 'Ikolomani', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wangaya, Christopher Aseka', 'Member of Parliament', 'Kakamega', 'Khwisero', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wangwe, Emmanuel', 'Member of Parliament', 'Kakamega', 'Navakholo', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wanjala, Raphael Sauti Bitta', 'Member of Parliament', 'Busia', 'Budalangi', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wetangula, Timothy Wanyonyi', 'Member of Parliament', 'Nairobi', 'Westlands', 'ODM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mupe, Anthony Kenga', 'Member of Parliament', 'Kilifi', 'Rabai', 'PAA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Rai, Samuel Gonzi', 'Member of Parliament', 'Kwale', 'Kinango', 'PAA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Tungule, Charo Kenneth Kazungu', 'Member of Parliament', 'Kilifi', 'Ganze', 'PAA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiunjuri, Festus Mwangi', 'Member of Parliament', 'Laikipia', 'Laikipia East', 'TSP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nduyo, Susan Ngugi', 'Member of Parliament', 'Tharaka-Nithi', 'Tharaka-Nithi(CWR)', 'TSP', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Akuja, Protus Ewesit', 'Member of Parliament', 'Turkana', 'Loima', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Alfah, Miruka Ondieki', 'Member of Parliament', 'Kisii', 'Bomachoge Chache', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ali, Abdisirat Khalif', 'Member of Parliament', 'Kenya', 'Nominated', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bader, Salim Feisal', 'Member of Parliament', 'Kwale', 'Msambweni', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Barre, Hussein Abdi', 'Member of Parliament', 'Wajir', 'Tarbaj', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Barrow, Dekow Mohamed', 'Member of Parliament', 'Garissa', 'Garissa Township', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bartoo, Phylis Jepkemoi', 'Member of Parliament', 'Uasin Gishu', 'Moiben', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Baya, Owen Yaa', 'Member of Parliament', 'Kilifi', 'Kilifi North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Biego, Paul Kibichy', 'Member of Parliament', 'Nandi', 'Chesumei', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bowen, David Kangogo', 'Member of Parliament', 'Elgeyo Marakwet', 'Marakwet East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chebor, Paul Kibet', 'Member of Parliament', 'Nakuru', 'Rongai', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chege, John Kiragu', 'Member of Parliament', 'Kiambu', 'Limuru', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chelule, Liza Chepkorir', 'Member of Parliament', 'Nakuru', 'Nakuru (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chepkonga, Kiprono Samwel', 'Member of Parliament', 'Uasin Gishu', 'Ainabkoi', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chepkorir, Linet', 'Member of Parliament', 'Bomet', 'Bomet (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chepkwony, Charity Kathambi', 'Member of Parliament', 'Nakuru', 'Njoro', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Cherorot, Joseph Kimutai', 'Member of Parliament', 'Kericho', 'Kipkelion East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chesebe, Fred Kapondi', 'Member of Parliament', 'Bungoma', 'Mt. Elgon', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chumel, Samwel Moroto', 'Member of Parliament', 'West Pokot', 'Kapenguria', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Double N, Pamela Njoki Njeru', 'Member of Parliament', 'Embu', 'Embu (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Emathe, Joseph Namuar', 'Member of Parliament', 'Turkana', 'Turkana Central', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gachagua, George N.', 'Member of Parliament', 'Nyandarua', 'Ndaragwa', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gachobe, Samuel Kinuthia', 'Member of Parliament', 'Nakuru', 'Subukia', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gakuya, James Mwangi', 'Member of Parliament', 'Nairobi', 'Embakasi North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gathiru, Mejjadonk Benjamin', 'Member of Parliament', 'Nairobi', 'Embakasi Central', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gichohi, Kaguchia John Philip', 'Member of Parliament', 'Nyeri', 'Mukurweini', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gichuki, Edwin Mugo', 'Member of Parliament', 'Murang''a', 'Mathioya', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gikaria, David', 'Member of Parliament', 'Nakuru', 'Nakuru Town East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gitari, Joseph Gachoki', 'Member of Parliament', 'Kirinyaga', 'Kirinyaga Central', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Gitau, Faith Wairimu', 'Member of Parliament', 'Nyandarua', 'Nyandarua (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Githinji, Robert Gichimu', 'Member of Parliament', 'Kirinyaga', 'Gichugu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('GK, George Macharia Kariuki', 'Member of Parliament', 'Kirinyaga', 'Ndia', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Hassan, Ahmed Maalim', 'Member of Parliament', 'Mandera', 'Banissa', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ichung’wah, Anthony Kimani', 'Member of Parliament', 'Kiambu', 'Kikuyu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ikiara, Dorothy Muthoni', 'Member of Parliament', 'Kenya', 'Nominated', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Iraya, Joseph Wainaina', 'Member of Parliament', 'Kenya', 'Nominated', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Jhanda Zaheer', 'Member of Parliament', 'Kisii', 'Nyaribari Chache', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kagiri, Jane Wangechi', 'Member of Parliament', 'Laikipia', 'Laikipia (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kagombe, Gabriel Gathuka', 'Member of Parliament', 'Kiambu', 'Gatundu South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kahangara, Joseph Mburu', 'Member of Parliament', 'Kiambu', 'Lari', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kahugu, Eric Meangi', 'Member of Parliament', 'Nyeri', 'Mathira', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kailema, Elizabeth Karambu', 'Member of Parliament', 'Meru', 'Meru (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kamuren, Charles', 'Member of Parliament', 'Baringo', 'Baringo South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kandie, Joshua Chepyegon', 'Member of Parliament', 'Baringo', 'Baringo Central', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Karani, Stephen Wachira', 'Member of Parliament', 'Laikipia', 'Laikipia West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Karemba, Eric Muchangi Njiru', 'Member of Parliament', 'Embu', 'Runyenjes', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kemei, Beatrice Chepng’eno', 'Member of Parliament', 'Kericho', 'Kericho (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kemei, Justice Kipsang', 'Member of Parliament', 'Kericho', 'Sigowet/Soin', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kemero, Maisori Marwa Kitayama', 'Member of Parliament', 'Migori', 'Kuria East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kihara, Jayne Wanjiru Njeru', 'Member of Parliament', 'Nakuru', 'Naivasha', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kihungi, Peter Irungu', 'Member of Parliament', 'Murang''a', 'Kangema', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kilel, Richard Cheruiyot', 'Member of Parliament', 'Bomet', 'Bomet Central', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kimani, Francis Kuria', 'Member of Parliament', 'Nakuru', 'Molo', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kingara, Simon Ng’ang’a', 'Member of Parliament', 'Kiambu', 'Ruiru', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipbiwot, Julius Melly', 'Member of Parliament', 'Nandi', 'Tinderet', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipgnor, Reuben Kiborek', 'Member of Parliament', 'Baringo', 'Mogotio', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipkoech, Gideon Kimaiyo', 'Member of Parliament', 'Elgeyo Marakwet', 'Keiyo South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipkoros, Joseph Makilap', 'Member of Parliament', 'Baringo', 'Baringo North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiplagat, David', 'Member of Parliament', 'Uasin Gishu', 'Soy', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiprono, Mutai Alfred', 'Member of Parliament', 'Nakuru', 'Kuresoi North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kipyegon, Johana Ng’eno', 'Member of Parliament', 'Narok', 'Emurua Dikirr', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kirima, Moses Nguchine', 'Member of Parliament', 'Meru', 'Central Imenti', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kirwa, Abraham Kipsang', 'Member of Parliament', 'Nandi', 'Mosop', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kitany, Marianne Jebet', 'Member of Parliament', 'Nandi', 'Aldai', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kitur, Bernard Kibor', 'Member of Parliament', 'Nandi', 'Nandi Hills', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Koech, Nelson', 'Member of Parliament', 'Kericho', 'Belgut', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Komingoi, Kibet Kirui', 'Member of Parliament', 'Kericho', 'Bureti', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Korir, Adams Kipsanai', 'Member of Parliament', 'Elgeyo Marakwet', 'Keiyo North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kosgei, Hilary Kiplangat', 'Member of Parliament', 'Kericho', 'Kipkelion West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kosgei, Jackson Kipkemoi', 'Member of Parliament', 'Kenya', 'Nominated', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Langat, Benjamin Kipkirui', 'Member of Parliament', 'Kericho', 'Ainamoi', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lelmengit, Josses Kiptoo Kosgey', 'Member of Parliament', 'Nandi', 'Emgwen', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lemanken, Aramat', 'Member of Parliament', 'Narok', 'Narok East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lenguris, Pauline', 'Member of Parliament', 'Samburu', 'Samburu (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Letipila, Dominic Eli', 'Member of Parliament', 'Samburu', 'Samburu North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lochakapong, Peter', 'Member of Parliament', 'West Pokot', 'Sigor', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Logova, Sloya Clement', 'Member of Parliament', 'Vihiga', 'Sabatia', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('M’Anaiba, Julius Taitumu', 'Member of Parliament', 'Meru', 'Igembe North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Maina, Betty Njeri', 'Member of Parliament', 'Murang’a', 'Murang’a (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Maina, Jane Njeri', 'Member of Parliament', 'Kirinyaga', 'Kirinyaga (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Maingi, Mary', 'Member of Parliament', 'Kirinyaga', 'Mwea', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mathenge, Duncan Maina', 'Member of Parliament', 'Nyeri', 'Nyeri Town', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mbai, Nimrod Mbithuka', 'Member of Parliament', 'Kitui', 'Kitui East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mbiuki, Japhet Miriti Kareke', 'Member of Parliament', 'Tharaka Nithi', 'Maara', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mizighi, Lydia Haika Mnene', 'Member of Parliament', 'Taita Taveta', 'Taita Taveta (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mohamed, Mohamed Ali', 'Member of Parliament', 'Mombasa', 'Nyali', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mokaya, Nyakundi Japheth', 'Member of Parliament', 'Kisii', 'Kitutu Chache North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muchira, Michael Mwangi', 'Member of Parliament', 'Nyandarua', 'Ol Jorok', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muge, Cynthia Jepkosgei', 'Member of Parliament', 'Nandi', 'Nandi (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muhia, Wanjiku', 'Member of Parliament', 'Nyandarua', 'Kipipiri', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mukunji, John Gitonga Mwaniki', 'Member of Parliament', 'Embu', 'Manyatta', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Munyoro, Joseph Kamau', 'Member of Parliament', 'Murang''a', 'Kigumo', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muratha, Anne Wanjiku Mugo', 'Member of Parliament', 'Kiambu', 'Kiambu (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Muriu, Wakili Edward', 'Member of Parliament', 'Murang''a', 'Gatanga', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Murugara, George Gitonga', 'Member of Parliament', 'Tharaka Nithi', 'Tharaka', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Murwithania, Rindikiri Mugambi', 'Member of Parliament', 'Meru', 'Buuri', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Musau, Vincent Musyoka', 'Member of Parliament', 'Machakos', 'Mwala', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mutua, Didmus Wekesa Barasa', 'Member of Parliament', 'Bungoma', 'Kimilili', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mutunga, John Kanyuithia', 'Member of Parliament', 'Meru', 'Tigania West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwafrika, Augustine Kamande', 'Member of Parliament', 'Nairobi', 'Royasambu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwangi, Geoffrey Wandeto', 'Member of Parliament', 'Nyeri', 'Tetu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwangi, Teresia Wanjiru', 'Member of Parliament', 'Kenya', 'Nominated', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwirigi, John Paul', 'Member of Parliament', 'Meru', 'Igembe South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nanok, Daniel Epuyo', 'Member of Parliament', 'Turkana', 'Turkana West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ndakwa, David Athman', 'Member of Parliament', 'Kakamega', 'Malava', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ndung’u George Koimburi', 'Member of Parliament', 'Kiambu', 'Juja', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ng’ang’a Alice Wambui', 'Member of Parliament', 'Kiambu', 'Thika Town', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ngitit, Cecilia Asinyen', 'Member of Parliament', 'Turkana', 'Turkana (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nguro, Onesmus Ngogoyo', 'Member of Parliament', 'Kajiado', 'Kajiado North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Njeru, Leo Wa Muthende', 'Member of Parliament', 'Embu', 'Mbeere North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Njoroge, Mary Wamaua Waithira', 'Member of Parliament', 'Murang''a', 'Maragwa', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Njuguna, Chege', 'Member of Parliament', 'Murang''a', 'Kandara', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Ntwiga, Patrick Munene', 'Member of Parliament', 'Tharaka Nithi', 'Chuka/Igambang’ombe', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyamoko, Joash Nyamache', 'Member of Parliament', 'Nyamira', 'North Mugirango', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyoro, Samson Ndindi', 'Member of Parliament', 'Murang''a', 'Kiharu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Onyiego, Silvanus Osoro', 'Member of Parliament', 'Kisii', 'South Mugirango', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Otucho, Mary Emaase', 'Member of Parliament', 'Busia', 'Teso South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Pukose, Robert (Dr.)', 'Member of Parliament', 'Trans Nzoia', 'Endebess', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Raso, Dido Ali', 'Member of Parliament', 'Marsabit', 'Saku', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Risa, Sunkuiya George', 'Member of Parliament', 'Kajiado', 'Kajiado West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Robi, Mathias Nyamabe', 'Member of Parliament', 'Migori', 'Kuria West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Rutto, Julius Kipletting', 'Member of Parliament', 'Uasin Gishu', 'Kesses', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Saney, Ibrahim Abdi', 'Member of Parliament', 'Wajir', 'Wajir North', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sankaire, Leah Sopiato', 'Member of Parliament', 'Kajiado', 'Kajiado (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sergon, Flowrence Jematiah', 'Member of Parliament', 'Baringo', 'Baringo (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Shollei, Gladys Jepkosgei Boss', 'Member of Parliament', 'Uasin Gishu', 'Uasin Gishu (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sigei, Francis Kipyegon arap', 'Member of Parliament', 'Bomet', 'Sotik', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sirma, Musa Cherutich', 'Member of Parliament', 'Baringo', 'Eldama Ravine', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sitati, Daniel Wanyama', 'Member of Parliament', 'Bungoma', 'Webuye West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sitienei, Janet Jepkemboi', 'Member of Parliament', 'Uasin Gishu', 'Turbo', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Siyoi, Lillian Chebet', 'Member of Parliament', 'Trans Nzoia', 'Trans Nzoia (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sudi, Oscar Kipchumba', 'Member of Parliament', 'Uasin Gishu', 'Kapseret', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Tongoyo, Gabriel Koshal', 'Member of Parliament', 'Narok', 'Narok West', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Tonkei, Rebecca Noonaishi', 'Member of Parliament', 'Narok', 'Narok (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Tonui, Joseph Kipkosgei', 'Member of Parliament', 'Nakuru', 'Kuresoi South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wachira, Rahab Mukami', 'Member of Parliament', 'Nyeri', 'Nyeri (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wainaina, Antony Njoroge', 'Member of Parliament', 'Nyeri', 'Kieni', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wainaina, Michael Wambugu', 'Member of Parliament', 'Nyeri', 'Othaya', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Waithaka, John Machua', 'Member of Parliament', 'Kiambu', 'Kiambu', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wamacukuru, James Githua Kamau', 'Member of Parliament', 'Kiambu', 'Kabete', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wamuchomba, Gathoni', 'Member of Parliament', 'Kiambu', 'Githunguri', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('John Njuguna', 'Member of Parliament', 'Kiambu', 'Kiambaa', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Wanjira, Martha Wangari', 'Member of Parliament', 'Nakuru', 'Gilgil', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Waqo, Naomi Jillo', 'Member of Parliament', 'Marsabit', 'Marsabit (CWR)', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Waweru, John Kiarie', 'Member of Parliament', 'Nairobi', 'Dagoretti South', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Yakub, Farah Salah', 'Member of Parliament', 'Garissa', 'Fafi', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Yegon, Brighton Leonard', 'Member of Parliament', 'Bomet', 'Konoin', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Yegon, Richard Kipkemoi', 'Member of Parliament', 'Bomet', 'Bomet East', 'UDA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdullahi, Bashir Sheikh', 'Member of Parliament', 'Mandera', 'Mandera North', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Chiforomodo, Mangale Munga', 'Member of Parliament', 'Kwale', 'Lungalunga', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Haro, Abdul Ebrahim', 'Member of Parliament', 'Mandera', 'Mandera South', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Harun, Suleka Hulbale', 'Member of Parliament', 'Kenya', 'Nominated', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Lekuton, Joseph', 'Member of Parliament', 'Marsabit', 'Laisamis', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Sheikh, Umul Ker Kassim', 'Member of Parliament', 'Mandera', 'Mandera (CWR)', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Yussuf, Adan Haji', 'Member of Parliament', 'Mandera', 'Mandera West', 'UDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Onchoke Charles', 'Member of Parliament', 'Kisii', 'Bonchari', 'UPA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Jaldesa, Guyo Waqo', 'Member of Parliament', 'Marsabit', 'Moyale', 'UPIA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Yakub, Adow Kuno', 'Member of Parliament', 'Tana River', 'Bura', 'UPIA', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Abdi, Khamis Chome', 'Member of Parliament', 'Taita Taveta', 'Voi', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Aburi, Donya Dorice', 'Member of Parliament', 'Kisii', 'Kisii (CWR)', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Basil, Robert Ngui', 'Member of Parliament', 'Machakos', 'Yatta', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Bwire, John Okano', 'Member of Parliament', 'Taita Taveta', 'Taveta', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kamene, Joyce', 'Member of Parliament', 'Machakos', 'Machakos (CWR)', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kasalu, Irene Muthoni', 'Member of Parliament', 'Kitui', 'Kitui (CWR)', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kiamba, Suzanne Ndunge', 'Member of Parliament', 'Makueni', 'Makueni', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Kimilu, Joshua Kivinda', 'Member of Parliament', 'Makueni', 'Kaiti', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('King’ola Patrick Makau', 'Member of Parliament', 'Machakos', 'Mavoko', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Maalim, Farah', 'Member of Parliament', 'Garissa', 'Dadaab', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mawathe, Julius Musili', 'Member of Parliament', 'Nairobi', 'Embakasi South', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mbalu, Jessica Nduku Kiko', 'Member of Parliament', 'Makueni', 'Kibwezi East', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mboni, David Mwalika', 'Member of Parliament', 'Kitui', 'Kitui Rural', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mbui, Robert', 'Member of Parliament', 'Machakos', 'Kathiani', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Momanyi, Innocent Obiri', 'Member of Parliament', 'Kisii', 'Bomachoge Borabu', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mule, Stephen Mutinda', 'Member of Parliament', 'Machakos', 'Matungulu', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mulu, Makali Benson', 'Member of Parliament', 'Kitui', 'Kitui Central', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mulyungi, Gideon Mutemi', 'Member of Parliament', 'Kitui', 'Mwingi Central', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mumo, Rose Museo', 'Member of Parliament', 'Makueni', 'Makueni (CWR)', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Mwakuwona, Danson Mwashako', 'Member of Parliament', 'Taita Taveta', 'Wundanyi', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nguna, Charles Ngusya', 'Member of Parliament', 'Kitui', 'Mwingi West', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nyenze, Edith Vethi', 'Member of Parliament', 'Kitui', 'Kitui West', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nzambia, Thudeeus Kithua', 'Member of Parliament', 'Makueni', 'Kilome', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nzengu, Paul Musyimi', 'Member of Parliament', 'Kitui', 'Mwingi North', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Nzioka, Erastus Kivasu', 'Member of Parliament', 'Makueni', 'Mbooni', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null),
  ('Twalib, Abubakar Ahmed', 'Member of Parliament', 'Kenya', 'Nominated', 'WDM', '2022-2027', 0, 0, 0, 0, null, null, null, null, null, null, null);
