"use client"

import { useState } from "react"
import type { County, Constituency } from "@/lib/enhanced-kenya-locations"

// Mock stalled projects data (in real app, this would come from the data pipeline)
const stalledProjectsData = [
  {
    id: 1,
    name: "Nairobi BRT System Phase 1",
    county: "Nairobi",
    constituency: "Westlands",
    sector: "Transport",
    budget: 45200000000,
    spent: 12800000000,
    stalledScore: 95,
    stalledStatus: "Confirmed Stalled",
    confidenceLevel: 92,
    monthsStalled: 18,
    issues: ["Contractor disputes", "Environmental concerns", "Budget overruns", "Land acquisition delays"],
    lastUpdate: "2025-05-15",
    expectedCompletion: "2022-12-31",
    startDate: "2019-03-15",
    contractor: "China Communications Construction Company",
    supervisor: "KeNHA",
    recommendations: [
      "Immediate project review and timeline reassessment required",
      "Consider appointing a project recovery manager",
      "Escalate to relevant authorities for intervention",
    ],
    coordinates: { lat: -1.2676, lng: 36.8108 },
  },
  {
    id: 2,
    name: "Nakuru Level 5 Hospital Expansion",
    county: "Nakuru",
    constituency: "Nakuru Town East",
    sector: "Health",
    budget: 3200000000,
    spent: 480000000,
    stalledScore: 88,
    stalledStatus: "Confirmed Stalled",
    confidenceLevel: 85,
    monthsStalled: 12,
    issues: ["Funding shortfall", "Design changes", "Contractor issues"],
    lastUpdate: "2025-03-10",
    expectedCompletion: "2024-02-15",
    startDate: "2021-02-15",
    contractor: "Local Construction Ltd",
    supervisor: "Ministry of Health",
    recommendations: [
      "Financial audit and budget reallocation needed",
      "Address audit findings immediately",
      "Increase public transparency and reporting",
    ],
    coordinates: { lat: -0.3031, lng: 36.1034 },
  },
  {
    id: 3,
    name: "Seme Irrigation Project",
    county: "Kisumu",
    constituency: "Seme",
    sector: "Agriculture",
    budget: 1200000000,
    spent: 240000000,
    stalledScore: 82,
    stalledStatus: "Confirmed Stalled",
    confidenceLevel: 78,
    monthsStalled: 8,
    issues: ["Land disputes", "Environmental clearance delays"],
    lastUpdate: "2025-04-15",
    expectedCompletion: "2024-08-31",
    startDate: "2021-09-01",
    contractor: "Agri-Tech Solutions",
    supervisor: "Ministry of Agriculture",
    recommendations: [
      "Initiate dispute resolution process",
      "Deploy field monitoring team",
      "Consider alternative contractors if necessary",
    ],
    coordinates: { lat: -0.1045, lng: 34.7345 },
  },
  {
    id: 4,
    name: "Mombasa Affordable Housing Project",
    county: "Mombasa",
    constituency: "Changamwe",
    sector: "Housing",
    budget: 5600000000,
    spent: 1680000000,
    stalledScore: 75,
    stalledStatus: "Likely Stalled",
    confidenceLevel: 82,
    monthsStalled: 6,
    issues: ["Material shortages", "Labor disputes", "Permit delays"],
    lastUpdate: "2025-04-28",
    expectedCompletion: "2025-12-31",
    startDate: "2022-01-10",
    contractor: "Coastal Construction Ltd",
    supervisor: "National Housing Corporation",
    recommendations: [
      "Establish mandatory weekly progress reporting",
      "Implement stricter financial controls",
      "Continue regular monitoring",
    ],
    coordinates: { lat: -4.0435, lng: 39.6682 },
  },
  {
    id: 5,
    name: "Turkana Wind Power Extension",
    county: "Turkana",
    constituency: "Loima",
    sector: "Energy",
    budget: 8900000000,
    spent: 2670000000,
    stalledScore: 68,
    stalledStatus: "At Risk",
    confidenceLevel: 75,
    monthsStalled: 4,
    issues: ["Technical challenges", "Access road problems"],
    lastUpdate: "2025-05-01",
    expectedCompletion: "2026-06-30",
    startDate: "2023-03-01",
    contractor: "Wind Energy Solutions",
    supervisor: "Ministry of Energy",
    recommendations: ["Continue regular monitoring", "Address technical challenges immediately"],
    coordinates: { lat: 3.1167, lng: 35.6167 },
  },
]

export default function StalledProjectsPage() {
  const [searchTerm, setSearchTerm] = useState("")
  const [selectedCounty, setSelectedCounty] = useState<County | null>(null)
  const [selectedConstituency, setSelectedConstituency] = useState<Constituency | null>(null)
  const [selectedSector, setSelectedSector] = useState<string | null>(null)
}
