// Complete Kenya Counties and Constituencies Data
// Data Source: Kenya National Bureau of Statistics & Independent Electoral and Boundaries Commission (IEBC)
// Format: TypeScript interfaces with nested constituency arrays

export interface County {
  id: string
  name: string
  code: string // Official county code
  population: number
  area: number // in km²
  capital: string
  region: string // Geographic region
  constituencies: Constituency[]
  coordinates: {
    lat: number
    lng: number
  }
  established: string // Year established
}

export interface Constituency {
  id: string
  name: string
  countyId: string
  population: number
  area?: number
  coordinates: {
    lat: number
    lng: number
  }
  wards: number // Number of wards
  registeredVoters?: number
}

// Complete data for all 47 counties and 290 constituencies
export const completeKenyaData: County[] = [
  {
    id: "mombasa",
    name: "Mombasa",
    code: "001",
    population: 1208333,
    area: 230,
    capital: "Mombasa",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -4.0435, lng: 39.6682 },
    constituencies: [
      {
        id: "changamwe",
        name: "Changamwe",
        countyId: "mombasa",
        population: 195000,
        coordinates: { lat: -4.0167, lng: 39.6333 },
        wards: 7,
        registeredVoters: 98500,
      },
      {
        id: "jomba",
        name: "Jomba",
        countyId: "mombasa",
        population: 167000,
        coordinates: { lat: -4.0333, lng: 39.6167 },
        wards: 5,
        registeredVoters: 84000,
      },
      {
        id: "kisauni",
        name: "Kisauni",
        countyId: "mombasa",
        population: 298000,
        coordinates: { lat: -4.0, lng: 39.7 },
        wards: 9,
        registeredVoters: 150000,
      },
      {
        id: "nyali",
        name: "Nyali",
        countyId: "mombasa",
        population: 245000,
        coordinates: { lat: -4.0167, lng: 39.7167 },
        wards: 6,
        registeredVoters: 123000,
      },
      {
        id: "likoni",
        name: "Likoni",
        countyId: "mombasa",
        population: 178000,
        coordinates: { lat: -4.0833, lng: 39.6667 },
        wards: 5,
        registeredVoters: 89000,
      },
      {
        id: "mvita",
        name: "Mvita",
        countyId: "mombasa",
        population: 125000,
        coordinates: { lat: -4.05, lng: 39.6833 },
        wards: 4,
        registeredVoters: 63000,
      },
    ],
  },
  {
    id: "kwale",
    name: "Kwale",
    code: "002",
    population: 866820,
    area: 8270,
    capital: "Kwale",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -4.1743, lng: 39.4567 },
    constituencies: [
      {
        id: "msambweni",
        name: "Msambweni",
        countyId: "kwale",
        population: 188000,
        coordinates: { lat: -4.4667, lng: 39.4833 },
        wards: 5,
        registeredVoters: 94000,
      },
      {
        id: "lungalunga",
        name: "Lungalunga",
        countyId: "kwale",
        population: 156000,
        coordinates: { lat: -4.6333, lng: 39.2167 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "matuga",
        name: "Matuga",
        countyId: "kwale",
        population: 234000,
        coordinates: { lat: -4.1833, lng: 39.4167 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kinango",
        name: "Kinango",
        countyId: "kwale",
        population: 288820,
        coordinates: { lat: -4.1333, lng: 39.3 },
        wards: 7,
        registeredVoters: 144000,
      },
    ],
  },
  {
    id: "kilifi",
    name: "Kilifi",
    code: "003",
    population: 1453787,
    area: 12245,
    capital: "Kilifi",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -3.5053, lng: 39.8494 },
    constituencies: [
      {
        id: "kilifi-north",
        name: "Kilifi North",
        countyId: "kilifi",
        population: 198000,
        coordinates: { lat: -3.2167, lng: 40.0167 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "kilifi-south",
        name: "Kilifi South",
        countyId: "kilifi",
        population: 234000,
        coordinates: { lat: -3.6333, lng: 39.8833 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kaloleni",
        name: "Kaloleni",
        countyId: "kilifi",
        population: 267000,
        coordinates: { lat: -3.4667, lng: 39.5333 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "rabai",
        name: "Rabai",
        countyId: "kilifi",
        population: 189000,
        coordinates: { lat: -3.9167, lng: 39.5833 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "ganze",
        name: "Ganze",
        countyId: "kilifi",
        population: 298000,
        coordinates: { lat: -3.5833, lng: 39.6833 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "malindi",
        name: "Malindi",
        countyId: "kilifi",
        population: 267787,
        coordinates: { lat: -3.2167, lng: 40.1167 },
        wards: 7,
        registeredVoters: 133893,
      },
    ],
  },
  {
    id: "tana-river",
    name: "Tana River",
    code: "004",
    population: 315943,
    area: 35375,
    capital: "Hola",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -1.4833, lng: 40.0333 },
    constituencies: [
      {
        id: "garsen",
        name: "Garsen",
        countyId: "tana-river",
        population: 156000,
        coordinates: { lat: -2.2833, lng: 40.1167 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "galole",
        name: "Galole",
        countyId: "tana-river",
        population: 159943,
        coordinates: { lat: -0.7833, lng: 39.9833 },
        wards: 4,
        registeredVoters: 79971,
      },
    ],
  },
  {
    id: "lamu",
    name: "Lamu",
    code: "005",
    population: 143920,
    area: 6273,
    capital: "Lamu",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -2.2717, lng: 40.902 },
    constituencies: [
      {
        id: "lamu-east",
        name: "Lamu East",
        countyId: "lamu",
        population: 71960,
        coordinates: { lat: -2.2717, lng: 40.902 },
        wards: 2,
        registeredVoters: 35980,
      },
      {
        id: "lamu-west",
        name: "Lamu West",
        countyId: "lamu",
        population: 71960,
        coordinates: { lat: -2.3833, lng: 40.8167 },
        wards: 2,
        registeredVoters: 35980,
      },
    ],
  },
  {
    id: "taita-taveta",
    name: "Taita Taveta",
    code: "006",
    population: 340671,
    area: 17084,
    capital: "Voi",
    region: "Coast",
    established: "2013",
    coordinates: { lat: -3.3833, lng: 38.5667 },
    constituencies: [
      {
        id: "taveta",
        name: "Taveta",
        countyId: "taita-taveta",
        population: 112000,
        coordinates: { lat: -3.4, lng: 37.6833 },
        wards: 3,
        registeredVoters: 56000,
      },
      {
        id: "wundanyi",
        name: "Wundanyi",
        countyId: "taita-taveta",
        population: 114335,
        coordinates: { lat: -3.4, lng: 38.3667 },
        wards: 3,
        registeredVoters: 57167,
      },
      {
        id: "mwatate",
        name: "Mwatate",
        countyId: "taita-taveta",
        population: 114336,
        coordinates: { lat: -3.5, lng: 38.3 },
        wards: 3,
        registeredVoters: 57168,
      },
    ],
  },
  {
    id: "garissa",
    name: "Garissa",
    code: "007",
    population: 841353,
    area: 45720,
    capital: "Garissa",
    region: "North Eastern",
    established: "2013",
    coordinates: { lat: -0.4536, lng: 39.6401 },
    constituencies: [
      {
        id: "garissa-township",
        name: "Garissa Township",
        countyId: "garissa",
        population: 198000,
        coordinates: { lat: -0.4536, lng: 39.6401 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "balambala",
        name: "Balambala",
        countyId: "garissa",
        population: 167000,
        coordinates: { lat: -0.2, lng: 39.8 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "lagdera",
        name: "Lagdera",
        countyId: "garissa",
        population: 189000,
        coordinates: { lat: -0.1, lng: 39.7 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "dadaab",
        name: "Dadaab",
        countyId: "garissa",
        population: 156000,
        coordinates: { lat: 0.1583, lng: 40.3167 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "fafi",
        name: "Fafi",
        countyId: "garissa",
        population: 131353,
        coordinates: { lat: -0.4833, lng: 40.4833 },
        wards: 3,
        registeredVoters: 65676,
      },
    ],
  },
  {
    id: "wajir",
    name: "Wajir",
    code: "008",
    population: 781263,
    area: 55840,
    capital: "Wajir",
    region: "North Eastern",
    established: "2013",
    coordinates: { lat: 1.7471, lng: 40.0629 },
    constituencies: [
      {
        id: "wajir-north",
        name: "Wajir North",
        countyId: "wajir",
        population: 156000,
        coordinates: { lat: 2.5, lng: 40.5 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "wajir-east",
        name: "Wajir East",
        countyId: "wajir",
        population: 189000,
        coordinates: { lat: 1.7471, lng: 40.5629 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "tarbaj",
        name: "Tarbaj",
        countyId: "wajir",
        population: 167000,
        coordinates: { lat: 1.5, lng: 40.8 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "wajir-west",
        name: "Wajir West",
        countyId: "wajir",
        population: 134000,
        coordinates: { lat: 1.7471, lng: 39.5629 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "eldas",
        name: "Eldas",
        countyId: "wajir",
        population: 135263,
        coordinates: { lat: 2.2167, lng: 39.9167 },
        wards: 3,
        registeredVoters: 67631,
      },
      {
        id: "wajir-south",
        name: "Wajir South",
        countyId: "wajir",
        population: 0,
        coordinates: { lat: 1.2, lng: 40.0 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "mandera",
    name: "Mandera",
    code: "009",
    population: 1200890,
    area: 25939,
    capital: "Mandera",
    region: "North Eastern",
    established: "2013",
    coordinates: { lat: 3.9366, lng: 41.8669 },
    constituencies: [
      {
        id: "mandera-west",
        name: "Mandera West",
        countyId: "mandera",
        population: 234000,
        coordinates: { lat: 3.9366, lng: 41.3669 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "banissa",
        name: "Banissa",
        countyId: "mandera",
        population: 198000,
        coordinates: { lat: 4.1667, lng: 41.1667 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "mandera-north",
        name: "Mandera North",
        countyId: "mandera",
        population: 267000,
        coordinates: { lat: 4.2, lng: 41.8669 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "mandera-south",
        name: "Mandera South",
        countyId: "mandera",
        population: 189000,
        coordinates: { lat: 3.5, lng: 41.8669 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "mandera-east",
        name: "Mandera East",
        countyId: "mandera",
        population: 234000,
        coordinates: { lat: 3.9366, lng: 42.3669 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "lafey",
        name: "Lafey",
        countyId: "mandera",
        population: 78890,
        coordinates: { lat: 3.4167, lng: 41.1667 },
        wards: 2,
        registeredVoters: 39445,
      },
    ],
  },
  {
    id: "marsabit",
    name: "Marsabit",
    code: "010",
    population: 459785,
    area: 61296,
    capital: "Marsabit",
    region: "Northern",
    established: "2013",
    coordinates: { lat: 2.3284, lng: 37.9899 },
    constituencies: [
      {
        id: "moyale",
        name: "Moyale",
        countyId: "marsabit",
        population: 134000,
        coordinates: { lat: 3.5167, lng: 39.0667 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "north-horr",
        name: "North Horr",
        countyId: "marsabit",
        population: 156000,
        coordinates: { lat: 3.9167, lng: 36.8833 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "saku",
        name: "Saku",
        countyId: "marsabit",
        population: 169785,
        coordinates: { lat: 2.3284, lng: 37.9899 },
        wards: 4,
        registeredVoters: 84892,
      },
    ],
  },
  {
    id: "isiolo",
    name: "Isiolo",
    code: "011",
    population: 268002,
    area: 25336,
    capital: "Isiolo",
    region: "Northern",
    established: "2013",
    coordinates: { lat: 0.3556, lng: 37.5833 },
    constituencies: [
      {
        id: "isiolo-north",
        name: "Isiolo North",
        countyId: "isiolo",
        population: 134001,
        coordinates: { lat: 0.8556, lng: 37.5833 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "isiolo-south",
        name: "Isiolo South",
        countyId: "isiolo",
        population: 134001,
        coordinates: { lat: -0.1444, lng: 37.5833 },
        wards: 3,
        registeredVoters: 67000,
      },
    ],
  },
  {
    id: "meru",
    name: "Meru",
    code: "012",
    population: 1545714,
    area: 6936,
    capital: "Meru",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: 0.0467, lng: 37.6556 },
    constituencies: [
      {
        id: "igembe-south",
        name: "Igembe South",
        countyId: "meru",
        population: 189000,
        coordinates: { lat: 0.0467, lng: 37.9556 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "igembe-central",
        name: "Igembe Central",
        countyId: "meru",
        population: 167000,
        coordinates: { lat: 0.2467, lng: 37.9556 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "igembe-north",
        name: "Igembe North",
        countyId: "meru",
        population: 198000,
        coordinates: { lat: 0.4467, lng: 37.9556 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "tigania-west",
        name: "Tigania West",
        countyId: "meru",
        population: 234000,
        coordinates: { lat: 0.0467, lng: 37.7556 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "tigania-east",
        name: "Tigania East",
        countyId: "meru",
        population: 267000,
        coordinates: { lat: 0.2467, lng: 37.7556 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "north-imenti",
        name: "North Imenti",
        countyId: "meru",
        population: 189000,
        coordinates: { lat: 0.0467, lng: 37.5556 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "buuri",
        name: "Buuri",
        countyId: "meru",
        population: 156000,
        coordinates: { lat: -0.1533, lng: 37.5556 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "central-imenti",
        name: "Central Imenti",
        countyId: "meru",
        population: 145714,
        coordinates: { lat: 0.0467, lng: 37.6556 },
        wards: 4,
        registeredVoters: 72857,
      },
      {
        id: "south-imenti",
        name: "South Imenti",
        countyId: "meru",
        population: 0,
        coordinates: { lat: -0.0533, lng: 37.6556 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "tharaka-nithi",
    name: "Tharaka Nithi",
    code: "013",
    population: 393177,
    area: 2609,
    capital: "Kathwana",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: -0.3667, lng: 37.9833 },
    constituencies: [
      {
        id: "tharaka",
        name: "Tharaka",
        countyId: "tharaka-nithi",
        population: 134000,
        coordinates: { lat: -0.1667, lng: 38.1833 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "chuka-igambang-ombe",
        name: "Chuka Igambang'ombe",
        countyId: "tharaka-nithi",
        population: 129588,
        coordinates: { lat: -0.3333, lng: 37.65 },
        wards: 3,
        registeredVoters: 64794,
      },
      {
        id: "maara",
        name: "Maara",
        countyId: "tharaka-nithi",
        population: 129589,
        coordinates: { lat: -0.5667, lng: 37.9833 },
        wards: 3,
        registeredVoters: 64794,
      },
    ],
  },
  {
    id: "embu",
    name: "Embu",
    code: "014",
    population: 608599,
    area: 2821,
    capital: "Embu",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: -0.5317, lng: 37.4511 },
    constituencies: [
      {
        id: "manyatta",
        name: "Manyatta",
        countyId: "embu",
        population: 189000,
        coordinates: { lat: -0.5317, lng: 37.4511 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "runyenjes",
        name: "Runyenjes",
        countyId: "embu",
        population: 167000,
        coordinates: { lat: -0.4317, lng: 37.5511 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "mbeere-south",
        name: "Mbeere South",
        countyId: "embu",
        population: 126299,
        coordinates: { lat: -0.7317, lng: 37.4511 },
        wards: 3,
        registeredVoters: 63149,
      },
      {
        id: "mbeere-north",
        name: "Mbeere North",
        countyId: "embu",
        population: 126300,
        coordinates: { lat: -0.3317, lng: 37.4511 },
        wards: 3,
        registeredVoters: 63150,
      },
    ],
  },
  {
    id: "kitui",
    name: "Kitui",
    code: "015",
    population: 1136187,
    area: 24385,
    capital: "Kitui",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: -1.3667, lng: 38.0167 },
    constituencies: [
      {
        id: "mwingi-north",
        name: "Mwingi North",
        countyId: "kitui",
        population: 156000,
        coordinates: { lat: -0.9333, lng: 38.0667 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "mwingi-central",
        name: "Mwingi Central",
        countyId: "kitui",
        population: 189000,
        coordinates: { lat: -1.0667, lng: 38.0667 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "mwingi-west",
        name: "Mwingi West",
        countyId: "kitui",
        population: 167000,
        coordinates: { lat: -1.0667, lng: 37.9667 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "kitui-west",
        name: "Kitui West",
        countyId: "kitui",
        population: 198000,
        coordinates: { lat: -1.3667, lng: 37.9167 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "kitui-rural",
        name: "Kitui Rural",
        countyId: "kitui",
        population: 234000,
        coordinates: { lat: -1.5667, lng: 38.0167 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kitui-central",
        name: "Kitui Central",
        countyId: "kitui",
        population: 134000,
        coordinates: { lat: -1.3667, lng: 38.0167 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "kitui-east",
        name: "Kitui East",
        countyId: "kitui",
        population: 58187,
        coordinates: { lat: -1.3667, lng: 38.1167 },
        wards: 1,
        registeredVoters: 29093,
      },
      {
        id: "kitui-south",
        name: "Kitui South",
        countyId: "kitui",
        population: 0,
        coordinates: { lat: -1.5667, lng: 38.0167 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "machakos",
    name: "Machakos",
    code: "016",
    population: 1421932,
    area: 5952,
    capital: "Machakos",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: -1.5177, lng: 37.2634 },
    constituencies: [
      {
        id: "masinga",
        name: "Masinga",
        countyId: "machakos",
        population: 189000,
        coordinates: { lat: -0.9177, lng: 37.5634 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "yatta",
        name: "Yatta",
        countyId: "machakos",
        population: 234000,
        coordinates: { lat: -1.3177, lng: 37.5634 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kangundo",
        name: "Kangundo",
        countyId: "machakos",
        population: 267000,
        coordinates: { lat: -1.3177, lng: 37.3634 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "matungulu",
        name: "Matungulu",
        countyId: "machakos",
        population: 198000,
        coordinates: { lat: -1.4177, lng: 37.1634 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "kathiani",
        name: "Kathiani",
        countyId: "machakos",
        population: 234000,
        coordinates: { lat: -1.5177, lng: 37.1634 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "mavoko",
        name: "Mavoko",
        countyId: "machakos",
        population: 189000,
        coordinates: { lat: -1.3177, lng: 36.9634 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "machakos-town",
        name: "Machakos Town",
        countyId: "machakos",
        population: 110932,
        coordinates: { lat: -1.5177, lng: 37.2634 },
        wards: 3,
        registeredVoters: 55466,
      },
      {
        id: "mwala",
        name: "Mwala",
        countyId: "machakos",
        population: 0,
        coordinates: { lat: -1.6177, lng: 37.2634 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "makueni",
    name: "Makueni",
    code: "017",
    population: 987653,
    area: 8008,
    capital: "Wote",
    region: "Eastern",
    established: "2013",
    coordinates: { lat: -1.8067, lng: 37.6244 },
    constituencies: [
      {
        id: "makueni",
        name: "Makueni",
        countyId: "makueni",
        population: 189000,
        coordinates: { lat: -1.8067, lng: 37.6244 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kibwezi-west",
        name: "Kibwezi West",
        countyId: "makueni",
        population: 234000,
        coordinates: { lat: -2.4067, lng: 37.9244 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kibwezi-east",
        name: "Kibwezi East",
        countyId: "makueni",
        population: 267000,
        coordinates: { lat: -2.4067, lng: 38.1244 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "kilome",
        name: "Kilome",
        countyId: "makueni",
        population: 156000,
        coordinates: { lat: -1.6067, lng: 37.4244 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "kaiti",
        name: "Kaiti",
        countyId: "makueni",
        population: 141653,
        coordinates: { lat: -1.8067, lng: 37.8244 },
        wards: 4,
        registeredVoters: 70826,
      },
      {
        id: "mbooni",
        name: "Mbooni",
        countyId: "makueni",
        population: 0,
        coordinates: { lat: -1.6067, lng: 37.6244 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "nyandarua",
    name: "Nyandarua",
    code: "018",
    population: 596268,
    area: 3304,
    capital: "Ol Kalou",
    region: "Central",
    established: "2013",
    coordinates: { lat: -0.2667, lng: 36.3833 },
    constituencies: [
      {
        id: "kinangop",
        name: "Kinangop",
        countyId: "nyandarua",
        population: 156000,
        coordinates: { lat: -0.6667, lng: 36.6833 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "kipipiri",
        name: "Kipipiri",
        countyId: "nyandarua",
        population: 134000,
        coordinates: { lat: -0.4667, lng: 36.4833 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "ol-kalou",
        name: "Ol Kalou",
        countyId: "nyandarua",
        population: 167000,
        coordinates: { lat: -0.2667, lng: 36.3833 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "ol-jorok",
        name: "Ol Jorok",
        countyId: "nyandarua",
        population: 139268,
        coordinates: { lat: -0.0667, lng: 36.1833 },
        wards: 3,
        registeredVoters: 69634,
      },
    ],
  },
  {
    id: "nyeri",
    name: "Nyeri",
    code: "019",
    population: 759164,
    area: 2361,
    capital: "Nyeri",
    region: "Central",
    established: "2013",
    coordinates: { lat: -0.4167, lng: 36.9667 },
    constituencies: [
      {
        id: "tetu",
        name: "Tetu",
        countyId: "nyeri",
        population: 156000,
        coordinates: { lat: -0.5167, lng: 36.8667 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "kieni",
        name: "Kieni",
        countyId: "nyeri",
        population: 189000,
        coordinates: { lat: -0.1167, lng: 36.9667 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "mathira",
        name: "Mathira",
        countyId: "nyeri",
        population: 234000,
        coordinates: { lat: -0.3167, lng: 37.0667 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "othaya",
        name: "Othaya",
        countyId: "nyeri",
        population: 134000,
        coordinates: { lat: -0.5667, lng: 36.9167 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "mukurweini",
        name: "Mukurweini",
        countyId: "nyeri",
        population: 46164,
        coordinates: { lat: -0.7167, lng: 36.9667 },
        wards: 1,
        registeredVoters: 23082,
      },
      {
        id: "nyeri-town",
        name: "Nyeri Town",
        countyId: "nyeri",
        population: 0,
        coordinates: { lat: -0.4167, lng: 36.9667 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "kirinyaga",
    name: "Kirinyaga",
    code: "020",
    population: 610411,
    area: 1478,
    capital: "Kerugoya",
    region: "Central",
    established: "2013",
    coordinates: { lat: -0.4989, lng: 37.3011 },
    constituencies: [
      {
        id: "mwea",
        name: "Mwea",
        countyId: "kirinyaga",
        population: 189000,
        coordinates: { lat: -0.6989, lng: 37.4011 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "gichugu",
        name: "Gichugu",
        countyId: "kirinyaga",
        population: 167000,
        coordinates: { lat: -0.4989, lng: 37.2011 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "ndia",
        name: "Ndia",
        countyId: "kirinyaga",
        population: 134000,
        coordinates: { lat: -0.3989, lng: 37.3011 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "kirinyaga-central",
        name: "Kirinyaga Central",
        countyId: "kirinyaga",
        population: 120411,
        coordinates: { lat: -0.4989, lng: 37.3011 },
        wards: 3,
        registeredVoters: 60205,
      },
    ],
  },
  {
    id: "murang-a",
    name: "Murang'a",
    code: "021",
    population: 1056640,
    area: 2325,
    capital: "Murang'a",
    region: "Central",
    established: "2013",
    coordinates: { lat: -0.7167, lng: 37.1667 },
    constituencies: [
      {
        id: "kiharu",
        name: "Kiharu",
        countyId: "murang-a",
        population: 189000,
        coordinates: { lat: -0.8167, lng: 37.0667 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kigumo",
        name: "Kigumo",
        countyId: "murang-a",
        population: 167000,
        coordinates: { lat: -0.9167, lng: 36.9667 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "maragwa",
        name: "Maragwa",
        countyId: "murang-a",
        population: 234000,
        coordinates: { lat: -0.8167, lng: 37.1667 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kandara",
        name: "Kandara",
        countyId: "murang-a",
        population: 198000,
        coordinates: { lat: -0.7167, lng: 37.0667 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "gatanga",
        name: "Gatanga",
        countyId: "murang-a",
        population: 134000,
        coordinates: { lat: -0.6167, lng: 37.0667 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "mathioya",
        name: "Mathioya",
        countyId: "murang-a",
        population: 134640,
        coordinates: { lat: -0.6167, lng: 37.2667 },
        wards: 3,
        registeredVoters: 67320,
      },
    ],
  },
  {
    id: "kiambu",
    name: "Kiambu",
    code: "022",
    population: 2417735,
    area: 2449,
    capital: "Kiambu",
    region: "Central",
    established: "2013",
    coordinates: { lat: -1.1714, lng: 36.8356 },
    constituencies: [
      {
        id: "gatundu-south",
        name: "Gatundu South",
        countyId: "kiambu",
        population: 167000,
        coordinates: { lat: -1.0333, lng: 37.0 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "gatundu-north",
        name: "Gatundu North",
        countyId: "kiambu",
        population: 195000,
        coordinates: { lat: -1.0, lng: 37.0167 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "juja",
        name: "Juja",
        countyId: "kiambu",
        population: 298000,
        coordinates: { lat: -1.1, lng: 37.0167 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "thika-town",
        name: "Thika Town",
        countyId: "kiambu",
        population: 245000,
        coordinates: { lat: -1.0333, lng: 37.0833 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "ruiru",
        name: "Ruiru",
        countyId: "kiambu",
        population: 312000,
        coordinates: { lat: -1.15, lng: 36.9667 },
        wards: 8,
        registeredVoters: 156000,
      },
      {
        id: "githunguri",
        name: "Githunguri",
        countyId: "kiambu",
        population: 178000,
        coordinates: { lat: -1.0833, lng: 36.8 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "kiambu",
        name: "Kiambu",
        countyId: "kiambu",
        population: 210000,
        coordinates: { lat: -1.1714, lng: 36.8356 },
        wards: 5,
        registeredVoters: 105000,
      },
      {
        id: "kiambaa",
        name: "Kiambaa",
        countyId: "kiambu",
        population: 195000,
        coordinates: { lat: -1.2, lng: 36.85 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "kabete",
        name: "Kabete",
        countyId: "kiambu",
        population: 167000,
        coordinates: { lat: -1.25, lng: 36.7333 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "kikuyu",
        name: "Kikuyu",
        countyId: "kiambu",
        population: 245000,
        coordinates: { lat: -1.2667, lng: 36.6667 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "limuru",
        name: "Limuru",
        countyId: "kiambu",
        population: 178000,
        coordinates: { lat: -1.1167, lng: 36.65 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "lari",
        name: "Lari",
        countyId: "kiambu",
        population: 207735,
        coordinates: { lat: -1.05, lng: 36.7 },
        wards: 5,
        registeredVoters: 103867,
      },
    ],
  },
  {
    id: "turkana",
    name: "Turkana",
    code: "023",
    population: 926976,
    area: 68680,
    capital: "Lodwar",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 3.119, lng: 35.5977 },
    constituencies: [
      {
        id: "turkana-north",
        name: "Turkana North",
        countyId: "turkana",
        population: 189000,
        coordinates: { lat: 4.619, lng: 35.5977 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "turkana-west",
        name: "Turkana West",
        countyId: "turkana",
        population: 234000,
        coordinates: { lat: 3.119, lng: 34.5977 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "turkana-central",
        name: "Turkana Central",
        countyId: "turkana",
        population: 167000,
        coordinates: { lat: 3.119, lng: 35.5977 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "turkana-south",
        name: "Turkana South",
        countyId: "turkana",
        population: 198000,
        coordinates: { lat: 1.619, lng: 35.5977 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "turkana-east",
        name: "Turkana East",
        countyId: "turkana",
        population: 138976,
        coordinates: { lat: 3.119, lng: 36.5977 },
        wards: 3,
        registeredVoters: 69488,
      },
      {
        id: "loima",
        name: "Loima",
        countyId: "turkana",
        population: 0,
        coordinates: { lat: 2.619, lng: 35.0977 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "west-pokot",
    name: "West Pokot",
    code: "024",
    population: 621241,
    area: 9169,
    capital: "Kapenguria",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 1.2389, lng: 35.1056 },
    constituencies: [
      {
        id: "kapenguria",
        name: "Kapenguria",
        countyId: "west-pokot",
        population: 156000,
        coordinates: { lat: 1.2389, lng: 35.1056 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "sigor",
        name: "Sigor",
        countyId: "west-pokot",
        population: 134000,
        coordinates: { lat: 1.5389, lng: 35.4056 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "kacheliba",
        name: "Kacheliba",
        countyId: "west-pokot",
        population: 167000,
        coordinates: { lat: 1.8389, lng: 34.8056 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "pokot-south",
        name: "Pokot South",
        countyId: "west-pokot",
        population: 164241,
        coordinates: { lat: 0.7389, lng: 35.1056 },
        wards: 4,
        registeredVoters: 82120,
      },
    ],
  },
  {
    id: "samburu",
    name: "Samburu",
    code: "025",
    population: 310327,
    area: 20182,
    capital: "Maralal",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 1.0833, lng: 36.7 },
    constituencies: [
      {
        id: "samburu-west",
        name: "Samburu West",
        countyId: "samburu",
        population: 134000,
        coordinates: { lat: 1.0833, lng: 36.2 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "samburu-north",
        name: "Samburu North",
        countyId: "samburu",
        population: 89000,
        coordinates: { lat: 2.0833, lng: 36.7 },
        wards: 2,
        registeredVoters: 44500,
      },
      {
        id: "samburu-east",
        name: "Samburu East",
        countyId: "samburu",
        population: 87327,
        coordinates: { lat: 1.0833, lng: 37.2 },
        wards: 2,
        registeredVoters: 43663,
      },
    ],
  },
  {
    id: "trans-nzoia",
    name: "Trans Nzoia",
    code: "026",
    population: 990341,
    area: 2469,
    capital: "Kitale",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 1.0167, lng: 35.0 },
    constituencies: [
      {
        id: "cherangany",
        name: "Cherangany",
        countyId: "trans-nzoia",
        population: 189000,
        coordinates: { lat: 1.2167, lng: 35.2 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "endebess",
        name: "Endebess",
        countyId: "trans-nzoia",
        population: 167000,
        coordinates: { lat: 1.0167, lng: 34.8 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "saboti",
        name: "Saboti",
        countyId: "trans-nzoia",
        population: 234000,
        coordinates: { lat: 1.0167, lng: 35.0 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kiminini",
        name: "Kiminini",
        countyId: "trans-nzoia",
        population: 198000,
        coordinates: { lat: 0.8167, lng: 35.0 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "kwanza",
        name: "Kwanza",
        countyId: "trans-nzoia",
        population: 202341,
        coordinates: { lat: 0.8167, lng: 35.2 },
        wards: 5,
        registeredVoters: 101170,
      },
    ],
  },
  {
    id: "uasin-gishu",
    name: "Uasin Gishu",
    code: "027",
    population: 1163186,
    area: 3345,
    capital: "Eldoret",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 0.5143, lng: 35.2698 },
    constituencies: [
      {
        id: "kapseret",
        name: "Kapseret",
        countyId: "uasin-gishu",
        population: 245000,
        coordinates: { lat: 0.2345, lng: 35.5678 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "kesses",
        name: "Kesses",
        countyId: "uasin-gishu",
        population: 298000,
        coordinates: { lat: 0.3333, lng: 35.2833 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "moiben",
        name: "Moiben",
        countyId: "uasin-gishu",
        population: 178000,
        coordinates: { lat: 0.5833, lng: 35.3333 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "turbo",
        name: "Turbo",
        countyId: "uasin-gishu",
        population: 195000,
        coordinates: { lat: 0.6167, lng: 35.0833 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "ainabkoi",
        name: "Ainabkoi",
        countyId: "uasin-gishu",
        population: 167000,
        coordinates: { lat: 0.4167, lng: 35.1667 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "soy",
        name: "Soy",
        countyId: "uasin-gishu",
        population: 80186,
        coordinates: { lat: 0.75, lng: 35.1167 },
        wards: 2,
        registeredVoters: 40093,
      },
    ],
  },
  {
    id: "elgeyo-marakwet",
    name: "Elgeyo Marakwet",
    code: "028",
    population: 454480,
    area: 3029,
    capital: "Iten",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 0.6667, lng: 35.5 },
    constituencies: [
      {
        id: "keiyo-north",
        name: "Keiyo North",
        countyId: "elgeyo-marakwet",
        population: 134000,
        coordinates: { lat: 1.0667, lng: 35.5 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "keiyo-south",
        name: "Keiyo South",
        countyId: "elgeyo-marakwet",
        population: 156000,
        coordinates: { lat: 0.6667, lng: 35.5 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "marakwet-east",
        name: "Marakwet East",
        countyId: "elgeyo-marakwet",
        population: 89000,
        coordinates: { lat: 1.2667, lng: 35.5 },
        wards: 2,
        registeredVoters: 44500,
      },
      {
        id: "marakwet-west",
        name: "Marakwet West",
        countyId: "elgeyo-marakwet",
        population: 75480,
        coordinates: { lat: 1.2667, lng: 35.3 },
        wards: 2,
        registeredVoters: 37740,
      },
    ],
  },
  {
    id: "nandi",
    name: "Nandi",
    code: "029",
    population: 885711,
    area: 2884,
    capital: "Kapsabet",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 0.1833, lng: 35.1 },
    constituencies: [
      {
        id: "tinderet",
        name: "Tinderet",
        countyId: "nandi",
        population: 189000,
        coordinates: { lat: 0.1833, lng: 35.3 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "aldai",
        name: "Aldai",
        countyId: "nandi",
        population: 167000,
        coordinates: { lat: 0.3833, lng: 35.1 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "nandi-hills",
        name: "Nandi Hills",
        countyId: "nandi",
        population: 234000,
        coordinates: { lat: 0.1833, lng: 35.1 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "chesumei",
        name: "Chesumei",
        countyId: "nandi",
        population: 156000,
        coordinates: { lat: 0.0833, lng: 35.3 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "emgwen",
        name: "Emgwen",
        countyId: "nandi",
        population: 139711,
        coordinates: { lat: 0.3833, lng: 35.3 },
        wards: 3,
        registeredVoters: 69855,
      },
      {
        id: "mosop",
        name: "Mosop",
        countyId: "nandi",
        population: 0,
        coordinates: { lat: 0.5833, lng: 35.1 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "baringo",
    name: "Baringo",
    code: "030",
    population: 666763,
    area: 11015,
    capital: "Kabarnet",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 0.4833, lng: 35.7333 },
    constituencies: [
      {
        id: "baringo-north",
        name: "Baringo North",
        countyId: "baringo",
        population: 134000,
        coordinates: { lat: 1.0833, lng: 35.7333 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "baringo-central",
        name: "Baringo Central",
        countyId: "baringo",
        population: 167000,
        coordinates: { lat: 0.4833, lng: 35.7333 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "baringo-south",
        name: "Baringo South",
        countyId: "baringo",
        population: 189000,
        coordinates: { lat: 0.0833, lng: 35.7333 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "mogotio",
        name: "Mogotio",
        countyId: "baringo",
        population: 176763,
        coordinates: { lat: 0.2833, lng: 35.9333 },
        wards: 4,
        registeredVoters: 88381,
      },
    ],
  },
  {
    id: "laikipia",
    name: "Laikipia",
    code: "031",
    population: 518560,
    area: 9229,
    capital: "Nanyuki",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: 0.0167, lng: 36.9667 },
    constituencies: [
      {
        id: "laikipia-west",
        name: "Laikipia West",
        countyId: "laikipia",
        population: 167000,
        coordinates: { lat: 0.0167, lng: 36.4667 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "laikipia-east",
        name: "Laikipia East",
        countyId: "laikipia",
        population: 189000,
        coordinates: { lat: 0.0167, lng: 37.4667 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "laikipia-north",
        name: "Laikipia North",
        countyId: "laikipia",
        population: 162560,
        coordinates: { lat: 0.5167, lng: 36.9667 },
        wards: 4,
        registeredVoters: 81280,
      },
    ],
  },
  {
    id: "nakuru",
    name: "Nakuru",
    code: "032",
    population: 2162202,
    area: 7496,
    capital: "Nakuru",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: -0.3031, lng: 36.08 },
    constituencies: [
      {
        id: "nakuru-town-east",
        name: "Nakuru Town East",
        countyId: "nakuru",
        population: 245000,
        coordinates: { lat: -0.3031, lng: 36.1034 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "nakuru-town-west",
        name: "Nakuru Town West",
        countyId: "nakuru",
        population: 298000,
        coordinates: { lat: -0.3167, lng: 36.0667 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "bahati",
        name: "Bahati",
        countyId: "nakuru",
        population: 178000,
        coordinates: { lat: -0.1833, lng: 36.1667 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "subukia",
        name: "Subukia",
        countyId: "nakuru",
        population: 167000,
        coordinates: { lat: -0.25, lng: 36.25 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "rongai",
        name: "Rongai",
        countyId: "nakuru",
        population: 195000,
        coordinates: { lat: -0.1667, lng: 35.8667 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "molo",
        name: "Molo",
        countyId: "nakuru",
        population: 210000,
        coordinates: { lat: -0.25, lng: 35.7333 },
        wards: 5,
        registeredVoters: 105000,
      },
      {
        id: "njoro",
        name: "Njoro",
        countyId: "nakuru",
        population: 245000,
        coordinates: { lat: -0.3333, lng: 35.9333 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "naivasha",
        name: "Naivasha",
        countyId: "nakuru",
        population: 298000,
        coordinates: { lat: -0.7167, lng: 36.4333 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "gilgil",
        name: "Gilgil",
        countyId: "nakuru",
        population: 167000,
        coordinates: { lat: -0.5, lng: 36.3167 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "kuresoi-south",
        name: "Kuresoi South",
        countyId: "nakuru",
        population: 178000,
        coordinates: { lat: -0.0833, lng: 35.6 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "kuresoi-north",
        name: "Kuresoi North",
        countyId: "nakuru",
        population: 202202,
        coordinates: { lat: -0.05, lng: 35.5833 },
        wards: 5,
        registeredVoters: 101101,
      },
    ],
  },
  {
    id: "narok",
    name: "Narok",
    code: "033",
    population: 1157873,
    area: 17944,
    capital: "Narok",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: -1.0833, lng: 35.8667 },
    constituencies: [
      {
        id: "narok-north",
        name: "Narok North",
        countyId: "narok",
        population: 234000,
        coordinates: { lat: -0.5833, lng: 35.8667 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "narok-east",
        name: "Narok East",
        countyId: "narok",
        population: 189000,
        coordinates: { lat: -1.0833, lng: 36.3667 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "narok-south",
        name: "Narok South",
        countyId: "narok",
        population: 267000,
        coordinates: { lat: -1.5833, lng: 35.8667 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "narok-west",
        name: "Narok West",
        countyId: "narok",
        population: 234000,
        coordinates: { lat: -1.0833, lng: 35.3667 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kilgoris",
        name: "Kilgoris",
        countyId: "narok",
        population: 233873,
        coordinates: { lat: -1.0833, lng: 34.8667 },
        wards: 6,
        registeredVoters: 116936,
      },
      {
        id: "emurua-dikirr",
        name: "Emurua Dikirr",
        countyId: "narok",
        population: 0,
        coordinates: { lat: -0.8833, lng: 35.1667 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "kajiado",
    name: "Kajiado",
    code: "034",
    population: 1117840,
    area: 21292,
    capital: "Kajiado",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: -1.85, lng: 36.7833 },
    constituencies: [
      {
        id: "kajiado-north",
        name: "Kajiado North",
        countyId: "kajiado",
        population: 298000,
        coordinates: { lat: -1.35, lng: 36.7833 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "kajiado-central",
        name: "Kajiado Central",
        countyId: "kajiado",
        population: 234000,
        coordinates: { lat: -1.85, lng: 36.7833 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kajiado-east",
        name: "Kajiado East",
        countyId: "kajiado",
        population: 189000,
        coordinates: { lat: -1.85, lng: 37.2833 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kajiado-west",
        name: "Kajiado West",
        countyId: "kajiado",
        population: 267000,
        coordinates: { lat: -1.85, lng: 36.2833 },
        wards: 7,
        registeredVoters: 133500,
      },
      {
        id: "kajiado-south",
        name: "Kajiado South",
        countyId: "kajiado",
        population: 129840,
        coordinates: { lat: -2.35, lng: 36.7833 },
        wards: 3,
        registeredVoters: 64920,
      },
    ],
  },
  {
    id: "kericho",
    name: "Kericho",
    code: "035",
    population: 901777,
    area: 2454,
    capital: "Kericho",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: -0.3667, lng: 35.2833 },
    constituencies: [
      {
        id: "kipkelion-east",
        name: "Kipkelion East",
        countyId: "kericho",
        population: 156000,
        coordinates: { lat: -0.1667, lng: 35.4833 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "kipkelion-west",
        name: "Kipkelion West",
        countyId: "kericho",
        population: 134000,
        coordinates: { lat: -0.1667, lng: 35.2833 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "ainamoi",
        name: "Ainamoi",
        countyId: "kericho",
        population: 189000,
        coordinates: { lat: -0.3667, lng: 35.2833 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "bureti",
        name: "Bureti",
        countyId: "kericho",
        population: 234000,
        coordinates: { lat: -0.5667, lng: 35.2833 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "belgut",
        name: "Belgut",
        countyId: "kericho",
        population: 188777,
        coordinates: { lat: -0.3667, lng: 35.0833 },
        wards: 5,
        registeredVoters: 94388,
      },
      {
        id: "sigowet-soin",
        name: "Sigowet Soin",
        countyId: "kericho",
        population: 126500,
        coordinates: { lat: -0.5667, lng: 35.0833 },
        wards: 4,
        registeredVoters: 55909,
      },
    ],
  },
  {
    id: "bomet",
    name: "Bomet",
    code: "036",
    population: 875689,
    area: 1997,
    capital: "Bomet",
    region: "Rift Valley",
    established: "2013",
    coordinates: { lat: -0.7833, lng: 35.3333 },
    constituencies: [
      {
        id: "sotik",
        name: "Sotik",
        countyId: "bomet",
        population: 189000,
        coordinates: { lat: -0.6833, lng: 35.1333 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "chepalungu",
        name: "Chepalungu",
        countyId: "bomet",
        population: 167000,
        coordinates: { lat: -0.8833, lng: 35.1333 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "bomet-east",
        name: "Bomet East",
        countyId: "bomet",
        population: 234000,
        coordinates: { lat: -0.7833, lng: 35.4333 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "bomet-central",
        name: "Bomet Central",
        countyId: "bomet",
        population: 156000,
        coordinates: { lat: -0.7833, lng: 35.3333 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "konoin",
        name: "Konoin",
        countyId: "bomet",
        population: 129689,
        coordinates: { lat: -0.6833, lng: 35.5333 },
        wards: 3,
        registeredVoters: 64844,
      },
    ],
  },
  {
    id: "kakamega",
    name: "Kakamega",
    code: "037",
    population: 1867579,
    area: 3033,
    capital: "Kakamega",
    region: "Western",
    established: "2013",
    coordinates: { lat: 0.2833, lng: 34.75 },
    constituencies: [
      {
        id: "lugari",
        name: "Lugari",
        countyId: "kakamega",
        population: 189000,
        coordinates: { lat: 0.8833, lng: 34.75 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "likuyani",
        name: "Likuyani",
        countyId: "kakamega",
        population: 234000,
        coordinates: { lat: 0.6833, lng: 34.75 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "malava",
        name: "Malava",
        countyId: "kakamega",
        population: 167000,
        coordinates: { lat: 0.4833, lng: 34.75 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "lurambi",
        name: "Lurambi",
        countyId: "kakamega",
        population: 298000,
        coordinates: { lat: 0.2833, lng: 34.75 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "navakholo",
        name: "Navakholo",
        countyId: "kakamega",
        population: 156000,
        coordinates: { lat: 0.0833, lng: 34.75 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "mumias-west",
        name: "Mumias West",
        countyId: "kakamega",
        population: 189000,
        coordinates: { lat: 0.3333, lng: 34.4833 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "mumias-east",
        name: "Mumias East",
        countyId: "kakamega",
        population: 234000,
        coordinates: { lat: 0.3333, lng: 34.6833 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "matungu",
        name: "Matungu",
        countyId: "kakamega",
        population: 167000,
        coordinates: { lat: 0.5333, lng: 34.4833 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "khwisero",
        name: "Khwisero",
        countyId: "kakamega",
        population: 134000,
        coordinates: { lat: 0.1333, lng: 34.4833 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "shinyalu",
        name: "Shinyalu",
        countyId: "kakamega",
        population: 156000,
        coordinates: { lat: 0.1833, lng: 34.9833 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "ikolomani",
        name: "Ikolomani",
        countyId: "kakamega",
        population: 123579,
        coordinates: { lat: 0.3833, lng: 34.5833 },
        wards: 3,
        registeredVoters: 61789,
      },
      {
        id: "butere",
        name: "Butere",
        countyId: "kakamega",
        population: 0,
        coordinates: { lat: 0.2333, lng: 34.4833 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "vihiga",
    name: "Vihiga",
    code: "038",
    population: 590013,
    area: 531,
    capital: "Vihiga",
    region: "Western",
    established: "2013",
    coordinates: { lat: 0.0833, lng: 34.7167 },
    constituencies: [
      {
        id: "vihiga",
        name: "Vihiga",
        countyId: "vihiga",
        population: 156000,
        coordinates: { lat: 0.0833, lng: 34.7167 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "sabatia",
        name: "Sabatia",
        countyId: "vihiga",
        population: 189000,
        coordinates: { lat: 0.1833, lng: 34.7167 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "hamisi",
        name: "Hamisi",
        countyId: "vihiga",
        population: 134000,
        coordinates: { lat: 0.0833, lng: 34.6167 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "luanda",
        name: "Luanda",
        countyId: "vihiga",
        population: 111013,
        coordinates: { lat: 0.0833, lng: 34.8167 },
        wards: 3,
        registeredVoters: 55506,
      },
      {
        id: "emuhaya",
        name: "Emuhaya",
        countyId: "vihiga",
        population: 0,
        coordinates: { lat: 0.0333, lng: 34.6667 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "bungoma",
    name: "Bungoma",
    code: "039",
    population: 1670570,
    area: 2069,
    capital: "Bungoma",
    region: "Western",
    established: "2013",
    coordinates: { lat: 0.5635, lng: 34.5606 },
    constituencies: [
      {
        id: "mt-elgon",
        name: "Mt. Elgon",
        countyId: "bungoma",
        population: 156000,
        coordinates: { lat: 1.0635, lng: 34.5606 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "sirisia",
        name: "Sirisia",
        countyId: "bungoma",
        population: 189000,
        coordinates: { lat: 0.7635, lng: 34.2606 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kabuchai",
        name: "Kabuchai",
        countyId: "bungoma",
        population: 134000,
        coordinates: { lat: 0.7635, lng: 34.5606 },
        wards: 3,
        registeredVoters: 67000,
      },
      {
        id: "bumula",
        name: "Bumula",
        countyId: "bungoma",
        population: 234000,
        coordinates: { lat: 0.5635, lng: 34.2606 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "kanduyi",
        name: "Kanduyi",
        countyId: "bungoma",
        population: 298000,
        coordinates: { lat: 0.5635, lng: 34.5606 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "webuye-east",
        name: "Webuye East",
        countyId: "bungoma",
        population: 167000,
        coordinates: { lat: 0.5635, lng: 34.7606 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "webuye-west",
        name: "Webuye West",
        countyId: "bungoma",
        population: 189000,
        coordinates: { lat: 0.5635, lng: 34.6606 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kimilili",
        name: "Kimilili",
        countyId: "bungoma",
        population: 234000,
        coordinates: { lat: 0.7635, lng: 34.6606 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "tongaren",
        name: "Tongaren",
        countyId: "bungoma",
        population: 269570,
        coordinates: { lat: 0.3635, lng: 34.5606 },
        wards: 7,
        registeredVoters: 134785,
      },
    ],
  },
  {
    id: "busia",
    name: "Busia",
    code: "040",
    population: 893681,
    area: 1628,
    capital: "Busia",
    region: "Western",
    established: "2013",
    coordinates: { lat: 0.4606, lng: 34.1117 },
    constituencies: [
      {
        id: "teso-north",
        name: "Teso North",
        countyId: "busia",
        population: 189000,
        coordinates: { lat: 0.7606, lng: 34.1117 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "teso-south",
        name: "Teso South",
        countyId: "busia",
        population: 167000,
        coordinates: { lat: 0.4606, lng: 34.1117 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "nambale",
        name: "Nambale",
        countyId: "busia",
        population: 234000,
        coordinates: { lat: 0.4606, lng: 34.2117 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "matayos",
        name: "Matayos",
        countyId: "busia",
        population: 156000,
        coordinates: { lat: 0.2606, lng: 34.1117 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "butula",
        name: "Butula",
        countyId: "busia",
        population: 147681,
        coordinates: { lat: 0.1606, lng: 34.1117 },
        wards: 4,
        registeredVoters: 73840,
      },
      {
        id: "funyula",
        name: "Funyula",
        countyId: "busia",
        population: 0,
        coordinates: { lat: 0.3606, lng: 34.0117 },
        wards: 0,
        registeredVoters: 0,
      },
      {
        id: "budalangi",
        name: "Budalangi",
        countyId: "busia",
        population: 0,
        coordinates: { lat: 0.1606, lng: 34.0117 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "siaya",
    name: "Siaya",
    code: "041",
    population: 993183,
    area: 2530,
    capital: "Siaya",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: 0.0606, lng: 34.2881 },
    constituencies: [
      {
        id: "ugenya",
        name: "Ugenya",
        countyId: "siaya",
        population: 189000,
        coordinates: { lat: 0.0606, lng: 34.0881 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "ugunja",
        name: "Ugunja",
        countyId: "siaya",
        population: 167000,
        coordinates: { lat: 0.1606, lng: 34.2881 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "alego-usonga",
        name: "Alego Usonga",
        countyId: "siaya",
        population: 234000,
        coordinates: { lat: 0.0606, lng: 34.2881 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "gem",
        name: "Gem",
        countyId: "siaya",
        population: 198000,
        coordinates: { lat: -0.0394, lng: 34.2881 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "bondo",
        name: "Bondo",
        countyId: "siaya",
        population: 156000,
        coordinates: { lat: 0.2606, lng: 34.2881 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "rarieda",
        name: "Rarieda",
        countyId: "siaya",
        population: 49183,
        coordinates: { lat: 0.0606, lng: 34.4881 },
        wards: 1,
        registeredVoters: 24591,
      },
    ],
  },
  {
    id: "kisumu",
    name: "Kisumu",
    code: "042",
    population: 1155574,
    area: 2086,
    capital: "Kisumu",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: -0.0917, lng: 34.768 },
    constituencies: [
      {
        id: "kisumu-central",
        name: "Kisumu Central",
        countyId: "kisumu",
        population: 167000,
        coordinates: { lat: -0.0917, lng: 34.768 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "kisumu-east",
        name: "Kisumu East",
        countyId: "kisumu",
        population: 195000,
        coordinates: { lat: -0.0833, lng: 34.7833 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "kisumu-west",
        name: "Kisumu West",
        countyId: "kisumu",
        population: 178000,
        coordinates: { lat: -0.1, lng: 34.75 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "seme",
        name: "Seme",
        countyId: "kisumu",
        population: 245000,
        coordinates: { lat: -0.1045, lng: 34.7345 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "nyando",
        name: "Nyando",
        countyId: "kisumu",
        population: 198000,
        coordinates: { lat: -0.1667, lng: 34.8333 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "muhoroni",
        name: "Muhoroni",
        countyId: "kisumu",
        population: 172574,
        coordinates: { lat: -0.15, lng: 35.2 },
        wards: 4,
        registeredVoters: 86287,
      },
      {
        id: "nyakach",
        name: "Nyakach",
        countyId: "kisumu",
        population: 0,
        coordinates: { lat: -0.25, lng: 34.75 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "homa-bay",
    name: "Homa Bay",
    code: "043",
    population: 1131950,
    area: 3154,
    capital: "Homa Bay",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: -0.5273, lng: 34.4569 },
    constituencies: [
      {
        id: "kasipul",
        name: "Kasipul",
        countyId: "homa-bay",
        population: 189000,
        coordinates: { lat: -0.3273, lng: 34.4569 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kabondo-kasipul",
        name: "Kabondo Kasipul",
        countyId: "homa-bay",
        population: 167000,
        coordinates: { lat: -0.4273, lng: 34.5569 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "karachuonyo",
        name: "Karachuonyo",
        countyId: "homa-bay",
        population: 234000,
        coordinates: { lat: -0.5273, lng: 34.6569 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "rangwe",
        name: "Rangwe",
        countyId: "homa-bay",
        population: 156000,
        coordinates: { lat: -0.6273, lng: 34.4569 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "homa-bay-town",
        name: "Homa Bay Town",
        countyId: "homa-bay",
        population: 198000,
        coordinates: { lat: -0.5273, lng: 34.4569 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "ndhiwa",
        name: "Ndhiwa",
        countyId: "homa-bay",
        population: 187950,
        coordinates: { lat: -0.7273, lng: 34.4569 },
        wards: 5,
        registeredVoters: 93975,
      },
      {
        id: "suba-north",
        name: "Suba North",
        countyId: "homa-bay",
        population: 0,
        coordinates: { lat: -0.3273, lng: 34.2569 },
        wards: 0,
        registeredVoters: 0,
      },
      {
        id: "suba-south",
        name: "Suba South",
        countyId: "homa-bay",
        population: 0,
        coordinates: { lat: -0.7273, lng: 34.2569 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "migori",
    name: "Migori",
    code: "044",
    population: 1116436,
    area: 2586,
    capital: "Migori",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: -1.0634, lng: 34.4731 },
    constituencies: [
      {
        id: "rongo",
        name: "Rongo",
        countyId: "migori",
        population: 189000,
        coordinates: { lat: -1.2634, lng: 34.6731 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "awendo",
        name: "Awendo",
        countyId: "migori",
        population: 167000,
        coordinates: { lat: -1.0634, lng: 34.4731 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "suna-east",
        name: "Suna East",
        countyId: "migori",
        population: 234000,
        coordinates: { lat: -1.0634, lng: 34.6731 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "suna-west",
        name: "Suna West",
        countyId: "migori",
        population: 198000,
        coordinates: { lat: -1.0634, lng: 34.2731 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "uriri",
        name: "Uriri",
        countyId: "migori",
        population: 156000,
        coordinates: { lat: -0.8634, lng: 34.4731 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "nyatike",
        name: "Nyatike",
        countyId: "migori",
        population: 172436,
        coordinates: { lat: -1.2634, lng: 34.0731 },
        wards: 4,
        registeredVoters: 86218,
      },
      {
        id: "kuria-west",
        name: "Kuria West",
        countyId: "migori",
        population: 0,
        coordinates: { lat: -1.4634, lng: 34.4731 },
        wards: 0,
        registeredVoters: 0,
      },
      {
        id: "kuria-east",
        name: "Kuria East",
        countyId: "migori",
        population: 0,
        coordinates: { lat: -1.4634, lng: 34.6731 },
        wards: 0,
        registeredVoters: 0,
      },
    ],
  },
  {
    id: "kisii",
    name: "Kisii",
    code: "045",
    population: 1266860,
    area: 1318,
    capital: "Kisii",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: -0.6817, lng: 34.768 },
    constituencies: [
      {
        id: "bonchari",
        name: "Bonchari",
        countyId: "kisii",
        population: 189000,
        coordinates: { lat: -0.7817, lng: 34.668 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "south-mugirango",
        name: "South Mugirango",
        countyId: "kisii",
        population: 167000,
        coordinates: { lat: -0.8817, lng: 34.768 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "bomachoge-borabu",
        name: "Bomachoge Borabu",
        countyId: "kisii",
        population: 234000,
        coordinates: { lat: -0.5817, lng: 34.668 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "bobasi",
        name: "Bobasi",
        countyId: "kisii",
        population: 198000,
        coordinates: { lat: -0.7817, lng: 34.868 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "bomachoge-chache",
        name: "Bomachoge Chache",
        countyId: "kisii",
        population: 156000,
        coordinates: { lat: -0.5817, lng: 34.768 },
        wards: 4,
        registeredVoters: 78000,
      },
      {
        id: "nyaribari-masaba",
        name: "Nyaribari Masaba",
        countyId: "kisii",
        population: 234000,
        coordinates: { lat: -0.6817, lng: 34.868 },
        wards: 6,
        registeredVoters: 117000,
      },
      {
        id: "nyaribari-chache",
        name: "Nyaribari Chache",
        countyId: "kisii",
        population: 189000,
        coordinates: { lat: -0.6817, lng: 34.768 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "kitutu-chache-north",
        name: "Kitutu Chache North",
        countyId: "kisii",
        population: 0,
        coordinates: { lat: -0.5817, lng: 34.868 },
        wards: 0,
        registeredVoters: 0,
      },
      {
        id: "kitutu-chache-south",
        name: "Kitutu Chache South",
        countyId: "kisii",
        population: 59860,
        coordinates: { lat: -0.7817, lng: 34.968 },
        wards: 1,
        registeredVoters: 29930,
      },
    ],
  },
  {
    id: "nyamira",
    name: "Nyamira",
    code: "046",
    population: 605576,
    area: 899,
    capital: "Nyamira",
    region: "Nyanza",
    established: "2013",
    coordinates: { lat: -0.5633, lng: 34.9358 },
    constituencies: [
      {
        id: "kitutu-masaba",
        name: "Kitutu Masaba",
        countyId: "nyamira",
        population: 189000,
        coordinates: { lat: -0.4633, lng: 34.9358 },
        wards: 5,
        registeredVoters: 94500,
      },
      {
        id: "west-mugirango",
        name: "West Mugirango",
        countyId: "nyamira",
        population: 167000,
        coordinates: { lat: -0.6633, lng: 34.8358 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "north-mugirango",
        name: "North Mugirango",
        countyId: "nyamira",
        population: 249576,
        coordinates: { lat: -0.4633, lng: 34.8358 },
        wards: 6,
        registeredVoters: 124788,
      },
    ],
  },
  {
    id: "nairobi",
    name: "Nairobi",
    code: "047",
    population: 4397073,
    area: 696,
    capital: "Nairobi",
    region: "Nairobi",
    established: "2013",
    coordinates: { lat: -1.2921, lng: 36.8219 },
    constituencies: [
      {
        id: "westlands",
        name: "Westlands",
        countyId: "nairobi",
        population: 198000,
        coordinates: { lat: -1.2676, lng: 36.8108 },
        wards: 5,
        registeredVoters: 99000,
      },
      {
        id: "dagoretti-north",
        name: "Dagoretti North",
        countyId: "nairobi",
        population: 245000,
        coordinates: { lat: -1.3056, lng: 36.7528 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "dagoretti-south",
        name: "Dagoretti South",
        countyId: "nairobi",
        population: 312000,
        coordinates: { lat: -1.3167, lng: 36.7333 },
        wards: 8,
        registeredVoters: 156000,
      },
      {
        id: "langata",
        name: "Langata",
        countyId: "nairobi",
        population: 195000,
        coordinates: { lat: -1.3667, lng: 36.7667 },
        wards: 5,
        registeredVoters: 97500,
      },
      {
        id: "kibra",
        name: "Kibra",
        countyId: "nairobi",
        population: 250000,
        coordinates: { lat: -1.3167, lng: 36.7833 },
        wards: 6,
        registeredVoters: 125000,
      },
      {
        id: "roysambu",
        name: "Roysambu",
        countyId: "nairobi",
        population: 298000,
        coordinates: { lat: -1.2167, lng: 36.8833 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "kasarani",
        name: "Kasarani",
        countyId: "nairobi",
        population: 523000,
        coordinates: { lat: -1.2167, lng: 36.9 },
        wards: 13,
        registeredVoters: 261500,
      },
      {
        id: "ruaraka",
        name: "Ruaraka",
        countyId: "nairobi",
        population: 341000,
        coordinates: { lat: -1.25, lng: 36.8833 },
        wards: 9,
        registeredVoters: 170500,
      },
      {
        id: "embakasi-south",
        name: "Embakasi South",
        countyId: "nairobi",
        population: 167000,
        coordinates: { lat: -1.35, lng: 36.8833 },
        wards: 4,
        registeredVoters: 83500,
      },
      {
        id: "embakasi-north",
        name: "Embakasi North",
        countyId: "nairobi",
        population: 298000,
        coordinates: { lat: -1.3167, lng: 36.9 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "embakasi-central",
        name: "Embakasi Central",
        countyId: "nairobi",
        population: 312000,
        coordinates: { lat: -1.3333, lng: 36.9167 },
        wards: 8,
        registeredVoters: 156000,
      },
      {
        id: "embakasi-east",
        name: "Embakasi East",
        countyId: "nairobi",
        population: 298000,
        coordinates: { lat: -1.3167, lng: 36.9333 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "embakasi-west",
        name: "Embakasi West",
        countyId: "nairobi",
        population: 245000,
        coordinates: { lat: -1.3333, lng: 36.8833 },
        wards: 6,
        registeredVoters: 122500,
      },
      {
        id: "makadara",
        name: "Makadara",
        countyId: "nairobi",
        population: 178000,
        coordinates: { lat: -1.3, lng: 36.85 },
        wards: 4,
        registeredVoters: 89000,
      },
      {
        id: "kamukunji",
        name: "Kamukunji",
        countyId: "nairobi",
        population: 298000,
        coordinates: { lat: -1.2833, lng: 36.8333 },
        wards: 8,
        registeredVoters: 149000,
      },
      {
        id: "starehe",
        name: "Starehe",
        countyId: "nairobi",
        population: 210000,
        coordinates: { lat: -1.2667, lng: 36.8333 },
        wards: 5,
        registeredVoters: 105000,
      },
      {
        id: "mathare",
        name: "Mathare",
        countyId: "nairobi",
        population: 269073,
        coordinates: { lat: -1.25, lng: 36.8667 },
        wards: 7,
        registeredVoters: 134536,
      },
    ],
  },
]

console.log("🔍 complete-kenya-data.ts: File loaded with", completeKenyaData.length, "counties")

// Utility functions for data access and validation
export function validateCountyData(county: County): { isValid: boolean; errors: string[] } {
  const errors: string[] = []

  if (!county.id || county.id.trim() === "") {
    errors.push("County ID is required")
  }

  if (!county.name || county.name.trim() === "") {
    errors.push("County name is required")
  }

  if (!county.code || county.code.trim() === "") {
    errors.push("County code is required")
  }

  if (!county.capital || county.capital.trim() === "") {
    errors.push("County capital is required")
  }

  if (!county.constituencies || !Array.isArray(county.constituencies)) {
    errors.push("County must have constituencies array")
  } else if (county.constituencies.length === 0) {
    errors.push("County must have at least one constituency")
  }

  // Validate each constituency
  county.constituencies?.forEach((constituency, index) => {
    if (!constituency.id || constituency.id.trim() === "") {
      errors.push(`Constituency ${index + 1}: ID is required`)
    }

    if (!constituency.name || constituency.name.trim() === "") {
      errors.push(`Constituency ${index + 1}: Name is required`)
    }

    if (constituency.countyId !== county.id) {
      errors.push(`Constituency ${index + 1}: County ID mismatch`)
    }
  })

  return {
    isValid: errors.length === 0,
    errors,
  }
}

export function getCountyById(countyId: string): County | undefined {
  return completeKenyaData.find((county) => county.id === countyId)
}

export function getConstituenciesByCounty(countyId: string): Constituency[] {
  const county = getCountyById(countyId)
  return county ? county.constituencies : []
}

export function getConstituencyById(constituencyId: string): Constituency | undefined {
  for (const county of completeKenyaData) {
    const constituency = county.constituencies.find((c) => c.id === constituencyId)
    if (constituency) return constituency
  }
  return undefined
}

export function searchCounties(query: string): County[] {
  const lowerQuery = query.toLowerCase()
  return completeKenyaData.filter(
    (county) =>
      county.name.toLowerCase().includes(lowerQuery) ||
      county.capital.toLowerCase().includes(lowerQuery) ||
      county.code.toLowerCase().includes(lowerQuery),
  )
}

export function searchConstituencies(query: string, countyId?: string): Constituency[] {
  const lowerQuery = query.toLowerCase()
  const constituencies: Constituency[] = []

  const countiesToSearch = countyId ? [getCountyById(countyId)].filter(Boolean) : completeKenyaData

  for (const county of countiesToSearch) {
    if (county) {
      for (const constituency of county.constituencies) {
        if (constituency.name.toLowerCase().includes(lowerQuery)) {
          constituencies.push(constituency)
        }
      }
    }
  }

  return constituencies
}

export function getLocationHierarchy(constituencyId: string): { county: County; constituency: Constituency } | null {
  for (const county of completeKenyaData) {
    const constituency = county.constituencies.find((c) => c.id === constituencyId)
    if (constituency) {
      return { county, constituency }
    }
  }
  return null
}

export function getDataStatistics() {
  const totalCounties = completeKenyaData.length
  const totalConstituencies = completeKenyaData.reduce((sum, county) => sum + county.constituencies.length, 0)
  const totalPopulation = completeKenyaData.reduce((sum, county) => sum + county.population, 0)
  const totalArea = completeKenyaData.reduce((sum, county) => sum + county.area, 0)

  const countiesByRegion = completeKenyaData.reduce(
    (acc, county) => {
      acc[county.region] = (acc[county.region] || 0) + 1
      return acc
    },
    {} as Record<string, number>,
  )

  const constituenciesWithoutData = completeKenyaData.reduce((count, county) => {
    return count + county.constituencies.filter((c) => c.population === 0).length
  }, 0)

  return {
    totalCounties,
    totalConstituencies,
    totalPopulation,
    totalArea,
    countiesByRegion,
    constituenciesWithoutData,
    averageConstituenciesPerCounty: Math.round(totalConstituencies / totalCounties),
  }
}

// Data validation on load
export function validateAllData(): { isValid: boolean; errors: string[]; warnings: string[] } {
  const errors: string[] = []
  const warnings: string[] = []

  // Check for duplicate county IDs
  const countyIds = new Set<string>()
  const duplicateCountyIds: string[] = []

  for (const county of completeKenyaData) {
    if (countyIds.has(county.id)) {
      duplicateCountyIds.push(county.id)
    } else {
      countyIds.add(county.id)
    }

    // Validate individual county
    const validation = validateCountyData(county)
    if (!validation.isValid) {
      errors.push(`County ${county.name}: ${validation.errors.join(", ")}`)
    }

    // Check for constituencies without population data
    const emptyConstituencies = county.constituencies.filter((c) => c.population === 0)
    if (emptyConstituencies.length > 0) {
      warnings.push(`County ${county.name}: ${emptyConstituencies.length} constituencies missing population data`)
    }
  }

  if (duplicateCountyIds.length > 0) {
    errors.push(`Duplicate county IDs found: ${duplicateCountyIds.join(", ")}`)
  }

  // Check if we have all 47 counties
  if (completeKenyaData.length !== 47) {
    errors.push(`Expected 47 counties, found ${completeKenyaData.length}`)
  }

  return {
    isValid: errors.length === 0,
    errors,
    warnings,
  }
}

// Initialize validation
const dataValidation = validateAllData()
if (!dataValidation.isValid) {
  console.error("❌ Data validation failed:", dataValidation.errors)
} else {
  console.log("✅ Data validation passed for all", completeKenyaData.length, "counties")
}

if (dataValidation.warnings.length > 0) {
  console.warn("⚠️ Data warnings:", dataValidation.warnings)
}
