import type { Senator } from "./types"

export const senatorsData: Senator[] = [
  {
    id: "1",
    name: "Mohamed Faki Mwinyihaji",
    county: "Mombasa",
    party: "ODM",
    role: "Head of Delegation",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "2",
    name: "Miraj Abdullahi Abdulrahman",
    county: "Mombasa",
    party: "UDA",
    role: "Member",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "3",
    name: "Crystal Kegehi Asige",
    county: "Mombasa",
    party: "ODM",
    role: "Member",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "4",
    name: "Issa Juma Boy",
    county: "Kwale",
    party: "ODM",
    role: "Head of Delegation",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "5",
    name: "Raphael Chimera Mwinzagu",
    county: "Kwale",
    party: "UDA",
    role: "Member",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "6",
    name: "Stewart Mwachiru Madzayo",
    county: "Kilifi",
    party: "ODM",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "7",
    name: "Danson Buya Mungatana",
    county: "Tana River",
    party: "UDA",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "8",
    name: "Joseph Githuku Kamau",
    county: "Lamu",
    party: "JUBILEE",
    role: "Head of Delegation",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "9",
    name: "Shakila Abdalla Mohamed",
    county: "Lamu",
    party: "WDM-K",
    role: "Member",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "10",
    name: "Johnes Mwashushe Mwaruma",
    county: "Taita Taveta",
    party: "ODM",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "11",
    name: "Abdul Mohammed Haji",
    county: "Garissa",
    party: "JUBILEE",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "12",
    name: "Sheikh Mohamed Abass",
    county: "Wajir",
    party: "UDM",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "13",
    name: "Ali Ibrahim Roba",
    county: "Mandera",
    party: "UDM",
    role: "Head of Delegation",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "14",
    name: "Mariam Sheikh Omar",
    county: "Mandera",
    party: "UDM",
    role: "Member",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "15",
    name: "Mohamed Said Chute",
    county: "Marsabit",
    party: "UDA",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "16",
    name: "Fatuma Dullo Adan",
    county: "Isiolo",
    party: "JUBILEE",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "17",
    name: "Murungi Kathuri",
    county: "Meru",
    party: "UDA",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "18",
    name: "Gataya Mo Fire Mwenda",
    county: "Tharaka Nithi",
    party: "UDA",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "19",
    name: "Alexander Munyi Mundigi",
    county: "Embu",
    party: "DP",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "20",
    name: "Enoch Kiio Wambua",
    county: "Kitui",
    party: "WDM-K",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
  {
    id: "21",
    name: "Agnes Kavindu Muthama",
    county: "Machakos",
    party: "WDM-K",
    role: "Senator",
    term: "2022-2027",
    phone: "",
    email: "",
    image: "/placeholder.svg?height=150&width=150",
  },
]
